# Generated by Django 5.0.7 on 2026-07-05 19:38

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text="Titre interne (jamais affiché aux visiteurs). Sert à organiser dans l'admin.", max_length=200)),
                ('link_url', models.URLField(blank=True, help_text='URL cible au clic. Vide = image non cliquable. Peut être interne (/programmes/prends-courage) ou externe.')),
                ('link_target', models.CharField(choices=[('_self', 'Même onglet'), ('_blank', 'Nouvel onglet')], default='_self', max_length=8)),
                ('alt_text', models.CharField(help_text="Description de l'image pour les lecteurs d'écran (accessibilité). Ex. « Campagne LIVE Zoom : Guérison et Restauration ».", max_length=200)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('starts_at', models.DateTimeField(blank=True, db_index=True, help_text='À partir de quand la bannière est visible. Vide = immédiatement.', null=True)),
                ('ends_at', models.DateTimeField(blank=True, db_index=True, help_text="Jusqu'à quand (strict). Vide = indéfiniment.", null=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text="Ordre d'apparition dans le carousel (plus petit = plus tôt).")),
            ],
            options={
                'verbose_name': 'Bannière',
                'verbose_name_plural': 'Bannières',
                'ordering': ['order', '-created_at'],
                'indexes': [models.Index(fields=['is_active', 'starts_at', 'ends_at'], name='banners_ban_is_acti_7354df_idx')],
            },
        ),
        migrations.CreateModel(
            name='HistoricalBanner',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('title', models.CharField(help_text="Titre interne (jamais affiché aux visiteurs). Sert à organiser dans l'admin.", max_length=200)),
                ('link_url', models.URLField(blank=True, help_text='URL cible au clic. Vide = image non cliquable. Peut être interne (/programmes/prends-courage) ou externe.')),
                ('link_target', models.CharField(choices=[('_self', 'Même onglet'), ('_blank', 'Nouvel onglet')], default='_self', max_length=8)),
                ('alt_text', models.CharField(help_text="Description de l'image pour les lecteurs d'écran (accessibilité). Ex. « Campagne LIVE Zoom : Guérison et Restauration ».", max_length=200)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('starts_at', models.DateTimeField(blank=True, db_index=True, help_text='À partir de quand la bannière est visible. Vide = immédiatement.', null=True)),
                ('ends_at', models.DateTimeField(blank=True, db_index=True, help_text="Jusqu'à quand (strict). Vide = indéfiniment.", null=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text="Ordre d'apparition dans le carousel (plus petit = plus tôt).")),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Bannière',
                'verbose_name_plural': 'historical Bannières',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='BannerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant', models.CharField(choices=[('mobile', 'Mobile (~750×1000, portrait)'), ('tablet', 'Tablette (~1024×500, paysage)'), ('desktop', 'Desktop bannière (~1920×540)'), ('ultrawide', 'Ultra-wide (~2560×600)')], max_length=16)),
                ('image', models.ImageField(height_field='height', upload_to='banners/', width_field='width')),
                ('width', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('height', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('min_viewport_width', models.PositiveIntegerField(blank=True, help_text='Largeur minimale de viewport (px) où cette image sera utilisée. Vide = valeur par défaut selon la variante (mobile=0, tablet=768, desktop=1280, ultrawide=1920).', null=True)),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='banners.banner')),
            ],
            options={
                'verbose_name': 'Image de bannière',
                'verbose_name_plural': 'Images de bannière',
                'ordering': ['banner', 'variant'],
                'unique_together': {('banner', 'variant')},
            },
        ),
    ]
