# Generated by Django 5.0.7 on 2026-07-10 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='alt_text',
            field=models.CharField(help_text="Description de l'image pour les lecteurs d'écran (accessibilité). Ex. « Campagne LIVE Zoom : Guérison et Restauration ».", max_length=200, verbose_name='Texte alternatif'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='ends_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text="Jusqu'à quand (strict). Vide = indéfiniment.", null=True, verbose_name="Visible jusqu'à"),
        ),
        migrations.AlterField(
            model_name='banner',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='link_target',
            field=models.CharField(choices=[('_self', 'Même onglet'), ('_blank', 'Nouvel onglet')], default='_self', max_length=8, verbose_name='Cible du lien'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='link_url',
            field=models.URLField(blank=True, help_text='URL cible au clic. Vide = image non cliquable. Peut être interne (/programmes/prends-courage) ou externe.', verbose_name='URL du lien'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text="Ordre d'apparition dans le carousel (plus petit = plus tôt).", verbose_name="Ordre d'affichage"),
        ),
        migrations.AlterField(
            model_name='banner',
            name='starts_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='À partir de quand la bannière est visible. Vide = immédiatement.', null=True, verbose_name='Visible à partir de'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(help_text="Titre interne (jamais affiché aux visiteurs). Sert à organiser dans l'admin.", max_length=200, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Modifié le'),
        ),
        migrations.AlterField(
            model_name='bannerimage',
            name='banner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='banners.banner', verbose_name='Bannière'),
        ),
        migrations.AlterField(
            model_name='bannerimage',
            name='height',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Hauteur'),
        ),
        migrations.AlterField(
            model_name='bannerimage',
            name='image',
            field=models.ImageField(height_field='height', upload_to='banners/', verbose_name='Image', width_field='width'),
        ),
        migrations.AlterField(
            model_name='bannerimage',
            name='min_viewport_width',
            field=models.PositiveIntegerField(blank=True, help_text='Largeur minimale de viewport (px) où cette image sera utilisée. Vide = valeur par défaut selon la variante (mobile=0, tablet=768, desktop=1280, ultrawide=1920).', null=True, verbose_name='Largeur minimale de viewport'),
        ),
        migrations.AlterField(
            model_name='bannerimage',
            name='variant',
            field=models.CharField(choices=[('mobile', 'Mobile (~750×1000, portrait)'), ('tablet', 'Tablette (~1024×500, paysage)'), ('desktop', 'Desktop bannière (~1920×540)'), ('ultrawide', 'Ultra-wide (~2560×600)')], max_length=16, verbose_name='Variante'),
        ),
        migrations.AlterField(
            model_name='bannerimage',
            name='width',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Largeur'),
        ),
        migrations.AlterField(
            model_name='historicalbanner',
            name='alt_text',
            field=models.CharField(help_text="Description de l'image pour les lecteurs d'écran (accessibilité). Ex. « Campagne LIVE Zoom : Guérison et Restauration ».", max_length=200, verbose_name='Texte alternatif'),
        ),
        migrations.AlterField(
            model_name='historicalbanner',
            name='created_at',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='historicalbanner',
            name='ends_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text="Jusqu'à quand (strict). Vide = indéfiniment.", null=True, verbose_name="Visible jusqu'à"),
        ),
        migrations.AlterField(
            model_name='historicalbanner',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='historicalbanner',
            name='link_target',
            field=models.CharField(choices=[('_self', 'Même onglet'), ('_blank', 'Nouvel onglet')], default='_self', max_length=8, verbose_name='Cible du lien'),
        ),
        migrations.AlterField(
            model_name='historicalbanner',
            name='link_url',
            field=models.URLField(blank=True, help_text='URL cible au clic. Vide = image non cliquable. Peut être interne (/programmes/prends-courage) ou externe.', verbose_name='URL du lien'),
        ),
        migrations.AlterField(
            model_name='historicalbanner',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text="Ordre d'apparition dans le carousel (plus petit = plus tôt).", verbose_name="Ordre d'affichage"),
        ),
        migrations.AlterField(
            model_name='historicalbanner',
            name='starts_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='À partir de quand la bannière est visible. Vide = immédiatement.', null=True, verbose_name='Visible à partir de'),
        ),
        migrations.AlterField(
            model_name='historicalbanner',
            name='title',
            field=models.CharField(help_text="Titre interne (jamais affiché aux visiteurs). Sert à organiser dans l'admin.", max_length=200, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='historicalbanner',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Modifié le'),
        ),
    ]
