# Generated by Django 5.0.7 on 2026-07-16 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0002_alter_banner_alt_text_alter_banner_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='alt_text',
            field=models.CharField(blank=True, help_text="Description de l'image pour les lecteurs d'écran (accessibilité). Ex. « Campagne LIVE Zoom : Guérison et Restauration ». Laissé vide, reprend le titre.", max_length=200, verbose_name='Texte alternatif'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(blank=True, help_text="Titre interne (jamais affiché aux visiteurs). Sert à organiser dans l'admin. Laissé vide, reprend le nom du fichier de la première image ajoutée.", max_length=200, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='historicalbanner',
            name='alt_text',
            field=models.CharField(blank=True, help_text="Description de l'image pour les lecteurs d'écran (accessibilité). Ex. « Campagne LIVE Zoom : Guérison et Restauration ». Laissé vide, reprend le titre.", max_length=200, verbose_name='Texte alternatif'),
        ),
        migrations.AlterField(
            model_name='historicalbanner',
            name='title',
            field=models.CharField(blank=True, help_text="Titre interne (jamais affiché aux visiteurs). Sert à organiser dans l'admin. Laissé vide, reprend le nom du fichier de la première image ajoutée.", max_length=200, verbose_name='Titre'),
        ),
    ]
