# Generated by Django 5.0.7 on 2026-07-18 07:05

import apps.banners.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0003_alter_banner_alt_text_alter_banner_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='title_is_auto',
            field=models.BooleanField(default=False, editable=False, help_text='Vrai si le titre a été rempli automatiquement depuis le nom du fichier (donc masqué sur le site public).', verbose_name='Titre auto-généré'),
        ),
        migrations.AddField(
            model_name='historicalbanner',
            name='title_is_auto',
            field=models.BooleanField(default=False, editable=False, help_text='Vrai si le titre a été rempli automatiquement depuis le nom du fichier (donc masqué sur le site public).', verbose_name='Titre auto-généré'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='link_url',
            field=models.CharField(blank=True, help_text='URL cible au clic. Vide = image non cliquable. Interne : commence par « / » (ex. /programmes/prends-courage — utilisez la liste de suggestions ci-dessous). Externe : URL complète (ex. https://exemple.com).', max_length=500, validators=[apps.banners.validators.validate_internal_or_external_url], verbose_name='URL du lien'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(blank=True, help_text="Titre affiché aux visiteurs sur la bannière. Laissé vide, reprend le nom du fichier de la première image ajoutée pour organiser l'admin — dans ce cas, rien ne s'affiche sur le carousel public.", max_length=200, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='historicalbanner',
            name='link_url',
            field=models.CharField(blank=True, help_text='URL cible au clic. Vide = image non cliquable. Interne : commence par « / » (ex. /programmes/prends-courage — utilisez la liste de suggestions ci-dessous). Externe : URL complète (ex. https://exemple.com).', max_length=500, validators=[apps.banners.validators.validate_internal_or_external_url], verbose_name='URL du lien'),
        ),
        migrations.AlterField(
            model_name='historicalbanner',
            name='title',
            field=models.CharField(blank=True, help_text="Titre affiché aux visiteurs sur la bannière. Laissé vide, reprend le nom du fichier de la première image ajoutée pour organiser l'admin — dans ce cas, rien ne s'affiche sur le carousel public.", max_length=200, verbose_name='Titre'),
        ),
    ]
