# Generated by Django 5.0.7 on 2026-07-07 08:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('endpoint', models.URLField(max_length=500, unique=True)),
                ('p256dh_key', models.CharField(help_text='Clé publique ECDH (base64url) fournie par le navigateur.', max_length=200)),
                ('auth_key', models.CharField(help_text="Secret d'authentification (base64url).", max_length=100)),
                ('user_agent', models.CharField(blank=True, max_length=280)),
                ('locale', models.CharField(default='fr', max_length=8)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('last_failure_at', models.DateTimeField(blank=True, null=True)),
                ('last_failure_status', models.PositiveIntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Abonnement push',
                'verbose_name_plural': 'Abonnements push',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PushCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('body', models.CharField(help_text='Texte de la notification (280 chars max — style tweet).', max_length=280)),
                ('icon', models.URLField(blank=True, help_text="URL d'icône affichée dans la notif (192×192 recommandé).")),
                ('image', models.URLField(blank=True, help_text="Grande image (optionnelle, s'affiche dans les notifs riches).")),
                ('url', models.CharField(blank=True, help_text='URL de destination au clic — chemin relatif (`/articles/...`) ou absolu (`https://ltltv.com/...`).', max_length=500)),
                ('audience', models.CharField(choices=[('all', 'Tous les abonnés'), ('authenticated', 'Utilisateurs connectés seulement')], default='all', max_length=20)),
                ('trigger_type', models.CharField(choices=[('manual', 'Composée manuellement'), ('article', 'Nouvel article'), ('episode', 'Nouvel épisode'), ('programme', 'Nouveau programme')], default='manual', max_length=20)),
                ('trigger_ref', models.CharField(blank=True, db_index=True, help_text="Référence unique de l'origine (ex : ``article:42``). Évite les doublons quand un contenu est modifié plusieurs fois.", max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('scheduled', 'Programmée'), ('sending', "En cours d'envoi"), ('sent', 'Envoyée'), ('failed', 'Échec')], db_index=True, default='draft', max_length=16)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('target_count', models.PositiveIntegerField(default=0, editable=False)),
                ('delivered_count', models.PositiveIntegerField(default=0, editable=False)),
                ('failed_count', models.PositiveIntegerField(default=0, editable=False)),
                ('click_count', models.PositiveIntegerField(default=0, editable=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='push_campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Campagne push',
                'verbose_name_plural': 'Campagnes push',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='notificatio_status_4ad383_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='pushcampaign',
            constraint=models.UniqueConstraint(condition=models.Q(('trigger_ref', ''), _negated=True), fields=('trigger_ref',), name='uniq_push_campaign_trigger_ref'),
        ),
        migrations.AddIndex(
            model_name='pushsubscription',
            index=models.Index(fields=['is_active', '-last_seen_at'], name='notificatio_is_acti_19b3a5_idx'),
        ),
        migrations.AddIndex(
            model_name='pushsubscription',
            index=models.Index(fields=['user'], name='notificatio_user_id_d7f78b_idx'),
        ),
    ]
