# Generated by Django 5.0.7 on 2026-07-10 17:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushcampaign',
            name='audience',
            field=models.CharField(choices=[('all', 'Tous les abonnés'), ('authenticated', 'Utilisateurs connectés seulement')], default='all', max_length=20, verbose_name='Audience'),
        ),
        migrations.AlterField(
            model_name='pushcampaign',
            name='body',
            field=models.CharField(help_text='Texte de la notification (280 chars max — style tweet).', max_length=280, verbose_name='Corps du message'),
        ),
        migrations.AlterField(
            model_name='pushcampaign',
            name='click_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Nombre de clics'),
        ),
        migrations.AlterField(
            model_name='pushcampaign',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='pushcampaign',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='push_campaigns', to=settings.AUTH_USER_MODEL, verbose_name='Créée par'),
        ),
        migrations.AlterField(
            model_name='pushcampaign',
            name='delivered_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Nombre de livraisons'),
        ),
        migrations.AlterField(
            model_name='pushcampaign',
            name='failed_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name="Nombre d'échecs"),
        ),
        migrations.AlterField(
            model_name='pushcampaign',
            name='icon',
            field=models.URLField(blank=True, help_text="URL d'icône affichée dans la notif (192×192 recommandé).", verbose_name='Icône'),
        ),
        migrations.AlterField(
            model_name='pushcampaign',
            name='image',
            field=models.URLField(blank=True, help_text="Grande image (optionnelle, s'affiche dans les notifs riches).", verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='pushcampaign',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Programmée pour le'),
        ),
        migrations.AlterField(
            model_name='pushcampaign',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Envoyée le'),
        ),
        migrations.AlterField(
            model_name='pushcampaign',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('scheduled', 'Programmée'), ('sending', "En cours d'envoi"), ('sent', 'Envoyée'), ('failed', 'Échec')], db_index=True, default='draft', max_length=16, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='pushcampaign',
            name='target_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Nombre de destinataires'),
        ),
        migrations.AlterField(
            model_name='pushcampaign',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='pushcampaign',
            name='trigger_ref',
            field=models.CharField(blank=True, db_index=True, help_text="Référence unique de l'origine (ex : ``article:42``). Évite les doublons quand un contenu est modifié plusieurs fois.", max_length=100, verbose_name='Référence du déclencheur'),
        ),
        migrations.AlterField(
            model_name='pushcampaign',
            name='trigger_type',
            field=models.CharField(choices=[('manual', 'Composée manuellement'), ('article', 'Nouvel article'), ('episode', 'Nouvel épisode'), ('programme', 'Nouveau programme')], default='manual', max_length=20, verbose_name='Type de déclencheur'),
        ),
        migrations.AlterField(
            model_name='pushcampaign',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Modifié le'),
        ),
        migrations.AlterField(
            model_name='pushcampaign',
            name='url',
            field=models.CharField(blank=True, help_text='URL de destination au clic — chemin relatif (`/articles/...`) ou absolu (`https://ltltv.com/...`).', max_length=500, verbose_name='URL de destination'),
        ),
        migrations.AlterField(
            model_name='pushsubscription',
            name='auth_key',
            field=models.CharField(help_text="Secret d'authentification (base64url).", max_length=100, verbose_name="Clé d'authentification"),
        ),
        migrations.AlterField(
            model_name='pushsubscription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='pushsubscription',
            name='endpoint',
            field=models.URLField(max_length=500, unique=True, verbose_name='Endpoint'),
        ),
        migrations.AlterField(
            model_name='pushsubscription',
            name='failed_count',
            field=models.PositiveIntegerField(default=0, verbose_name="Nombre d'échecs"),
        ),
        migrations.AlterField(
            model_name='pushsubscription',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='pushsubscription',
            name='last_failure_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Dernier échec le'),
        ),
        migrations.AlterField(
            model_name='pushsubscription',
            name='last_failure_status',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Code du dernier échec'),
        ),
        migrations.AlterField(
            model_name='pushsubscription',
            name='last_seen_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Vu pour la dernière fois le'),
        ),
        migrations.AlterField(
            model_name='pushsubscription',
            name='locale',
            field=models.CharField(default='fr', max_length=8, verbose_name='Langue'),
        ),
        migrations.AlterField(
            model_name='pushsubscription',
            name='p256dh_key',
            field=models.CharField(help_text='Clé publique ECDH (base64url) fournie par le navigateur.', max_length=200, verbose_name='Clé P256DH'),
        ),
        migrations.AlterField(
            model_name='pushsubscription',
            name='unsubscribed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Désabonné le'),
        ),
        migrations.AlterField(
            model_name='pushsubscription',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Modifié le'),
        ),
        migrations.AlterField(
            model_name='pushsubscription',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AlterField(
            model_name='pushsubscription',
            name='user_agent',
            field=models.CharField(blank=True, max_length=280, verbose_name='Navigateur'),
        ),
    ]
