# Generated by Django 5.0.7 on 2026-07-06 09:21

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temoignages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalTestimonial',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('slug', models.SlugField(blank=True, max_length=220)),
                ('author_name', models.CharField(help_text='Prénom + initiale (ex : Sarah M.).', max_length=120)),
                ('author_email', models.EmailField(blank=True, help_text='Interne uniquement — jamais affiché publiquement. Sert au suivi.', max_length=254)),
                ('author_phone', models.CharField(blank=True, help_text='Interne uniquement.', max_length=32)),
                ('country', models.CharField(blank=True, help_text='Ex : RDC, France, Belgique.', max_length=80)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('title', models.CharField(blank=True, help_text="Titre optionnel du témoignage (ex : « Comment j'ai retrouvé la paix »).", max_length=200)),
                ('story_short', models.CharField(blank=True, help_text='Résumé pour vignettes (auto-tronqué depuis `story` si vide).', max_length=280)),
                ('story', models.TextField(help_text='Le témoignage complet.')),
                ('photo', models.TextField(blank=True, max_length=100, null=True)),
                ('is_photo_public', models.BooleanField(default=True, help_text="L'auteur autorise l'affichage public de sa photo.")),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Rejeté'), ('archived', 'Archivé')], db_index=True, default='pending', max_length=16)),
                ('moderation_note', models.TextField(blank=True, help_text='Note interne (raison de rejet, remarque). Jamais publique.')),
                ('moderated_at', models.DateTimeField(blank=True, null=True)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('submitted_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('submitted_user_agent', models.CharField(blank=True, max_length=280)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('moderated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Témoignage',
                'verbose_name_plural': 'historical Témoignages',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('author_name', models.CharField(help_text='Prénom + initiale (ex : Sarah M.).', max_length=120)),
                ('author_email', models.EmailField(blank=True, help_text='Interne uniquement — jamais affiché publiquement. Sert au suivi.', max_length=254)),
                ('author_phone', models.CharField(blank=True, help_text='Interne uniquement.', max_length=32)),
                ('country', models.CharField(blank=True, help_text='Ex : RDC, France, Belgique.', max_length=80)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('title', models.CharField(blank=True, help_text="Titre optionnel du témoignage (ex : « Comment j'ai retrouvé la paix »).", max_length=200)),
                ('story_short', models.CharField(blank=True, help_text='Résumé pour vignettes (auto-tronqué depuis `story` si vide).', max_length=280)),
                ('story', models.TextField(help_text='Le témoignage complet.')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='temoignages/')),
                ('is_photo_public', models.BooleanField(default=True, help_text="L'auteur autorise l'affichage public de sa photo.")),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Rejeté'), ('archived', 'Archivé')], db_index=True, default='pending', max_length=16)),
                ('moderation_note', models.TextField(blank=True, help_text='Note interne (raison de rejet, remarque). Jamais publique.')),
                ('moderated_at', models.DateTimeField(blank=True, null=True)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('submitted_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('submitted_user_agent', models.CharField(blank=True, max_length=280)),
                ('moderated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_testimonials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Témoignage',
                'verbose_name_plural': 'Témoignages',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Temoignage',
        ),
        migrations.AddIndex(
            model_name='testimonial',
            index=models.Index(fields=['status', 'is_featured'], name='temoignages_status_931c81_idx'),
        ),
        migrations.AddIndex(
            model_name='testimonial',
            index=models.Index(fields=['status', '-created_at'], name='temoignages_status_a39238_idx'),
        ),
    ]
