# Generated by Django 5.0.7 on 2026-07-10 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temoignages', '0002_replace_temoignage_with_testimonial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltestimonial',
            name='author_email',
            field=models.EmailField(blank=True, help_text='Interne uniquement — jamais affiché publiquement. Sert au suivi.', max_length=254, verbose_name='Email (privé)'),
        ),
        migrations.AlterField(
            model_name='historicaltestimonial',
            name='author_name',
            field=models.CharField(help_text='Prénom + initiale du nom (ex : Sarah M.).', max_length=120, verbose_name='Nom affiché'),
        ),
        migrations.AlterField(
            model_name='historicaltestimonial',
            name='author_phone',
            field=models.CharField(blank=True, help_text='Interne uniquement.', max_length=32, verbose_name='Téléphone (privé)'),
        ),
        migrations.AlterField(
            model_name='historicaltestimonial',
            name='city',
            field=models.CharField(blank=True, max_length=120, verbose_name='Ville'),
        ),
        migrations.AlterField(
            model_name='historicaltestimonial',
            name='country',
            field=models.CharField(blank=True, help_text='Ex : RDC, France, Belgique.', max_length=80, verbose_name='Pays'),
        ),
        migrations.AlterField(
            model_name='historicaltestimonial',
            name='created_at',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='historicaltestimonial',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Mis en avant'),
        ),
        migrations.AlterField(
            model_name='historicaltestimonial',
            name='is_photo_public',
            field=models.BooleanField(default=True, help_text="L'auteur a-t-il autorisé l'affichage public de sa photo ?", verbose_name='Photo publique autorisée'),
        ),
        migrations.AlterField(
            model_name='historicaltestimonial',
            name='moderated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Modéré le'),
        ),
        migrations.AlterField(
            model_name='historicaltestimonial',
            name='moderated_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Modéré par'),
        ),
        migrations.AlterField(
            model_name='historicaltestimonial',
            name='moderation_note',
            field=models.TextField(blank=True, help_text='Raison de rejet, remarque… Jamais visible publiquement.', verbose_name='Note interne'),
        ),
        migrations.AlterField(
            model_name='historicaltestimonial',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage"),
        ),
        migrations.AlterField(
            model_name='historicaltestimonial',
            name='photo',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='historicaltestimonial',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='historicaltestimonial',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Rejeté'), ('archived', 'Archivé')], db_index=True, default='pending', max_length=16, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='historicaltestimonial',
            name='story',
            field=models.TextField(help_text='Le récit complet.', verbose_name='Témoignage complet'),
        ),
        migrations.AlterField(
            model_name='historicaltestimonial',
            name='story_short',
            field=models.CharField(blank=True, help_text='Auto-généré depuis le témoignage si laissé vide.', max_length=280, verbose_name='Résumé court'),
        ),
        migrations.AlterField(
            model_name='historicaltestimonial',
            name='submitted_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP'),
        ),
        migrations.AlterField(
            model_name='historicaltestimonial',
            name='submitted_user_agent',
            field=models.CharField(blank=True, max_length=280, verbose_name='Navigateur'),
        ),
        migrations.AlterField(
            model_name='historicaltestimonial',
            name='title',
            field=models.CharField(blank=True, help_text="Optionnel (ex : « Comment j'ai retrouvé la paix »).", max_length=200, verbose_name='Titre du témoignage'),
        ),
        migrations.AlterField(
            model_name='historicaltestimonial',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Modifié le'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='author_email',
            field=models.EmailField(blank=True, help_text='Interne uniquement — jamais affiché publiquement. Sert au suivi.', max_length=254, verbose_name='Email (privé)'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='author_name',
            field=models.CharField(help_text='Prénom + initiale du nom (ex : Sarah M.).', max_length=120, verbose_name='Nom affiché'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='author_phone',
            field=models.CharField(blank=True, help_text='Interne uniquement.', max_length=32, verbose_name='Téléphone (privé)'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='city',
            field=models.CharField(blank=True, max_length=120, verbose_name='Ville'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='country',
            field=models.CharField(blank=True, help_text='Ex : RDC, France, Belgique.', max_length=80, verbose_name='Pays'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Mis en avant'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='is_photo_public',
            field=models.BooleanField(default=True, help_text="L'auteur a-t-il autorisé l'affichage public de sa photo ?", verbose_name='Photo publique autorisée'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='moderated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Modéré le'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='moderated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_testimonials', to=settings.AUTH_USER_MODEL, verbose_name='Modéré par'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='moderation_note',
            field=models.TextField(blank=True, help_text='Raison de rejet, remarque… Jamais visible publiquement.', verbose_name='Note interne'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage"),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='temoignages/', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Rejeté'), ('archived', 'Archivé')], db_index=True, default='pending', max_length=16, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='story',
            field=models.TextField(help_text='Le récit complet.', verbose_name='Témoignage complet'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='story_short',
            field=models.CharField(blank=True, help_text='Auto-généré depuis le témoignage si laissé vide.', max_length=280, verbose_name='Résumé court'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='submitted_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='submitted_user_agent',
            field=models.CharField(blank=True, max_length=280, verbose_name='Navigateur'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='title',
            field=models.CharField(blank=True, help_text="Optionnel (ex : « Comment j'ai retrouvé la paix »).", max_length=200, verbose_name='Titre du témoignage'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Modifié le'),
        ),
    ]
