# Generated by Django 5.0.7 on 2026-07-10 18:17

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('meta_title', models.CharField(blank=True, help_text='Titre HTML (≤ 70 caractères). Si vide, `title` est utilisé.', max_length=70, verbose_name='Titre SEO')),
                ('meta_description', models.CharField(blank=True, help_text='Description meta (≤ 180 caractères).', max_length=180, verbose_name='Description SEO')),
                ('og_image', models.ImageField(blank=True, help_text='Image Open Graph (1200×630 recommandé).', null=True, upload_to='seo/og/', verbose_name='Image Open Graph')),
                ('canonical_url', models.URLField(blank=True, help_text='URL canonique (si le contenu est syndiqué depuis une autre source).', verbose_name='URL canonique')),
                ('mission', models.TextField(blank=True, help_text='Ce que LTL·TV cherche à accomplir au quotidien.', verbose_name='Mission')),
                ('vision', models.TextField(blank=True, help_text='Où LTL·TV se projette à long terme.', verbose_name='Vision')),
                ('history_text', models.TextField(blank=True, help_text="Le récit de la création et de l'évolution de la chaîne.", verbose_name='Histoire')),
                ('founded_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Année de création')),
                ('cover', models.ImageField(blank=True, help_text='Bannière affichée en tête de la page « À propos ».', null=True, upload_to='about/', verbose_name='Image de couverture')),
            ],
            options={
                'verbose_name': 'Page « À propos »',
                'verbose_name_plural': 'Page « À propos »',
            },
        ),
        migrations.CreateModel(
            name='CoreValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('title', models.CharField(max_length=120, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('icon', models.CharField(blank=True, help_text="Nom d'icône lucide-react (ex : heart, book-open, users, compass).", max_length=48, verbose_name='Icône')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Valeur',
                'verbose_name_plural': 'Valeurs',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalAboutPage',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Modifié le')),
                ('meta_title', models.CharField(blank=True, help_text='Titre HTML (≤ 70 caractères). Si vide, `title` est utilisé.', max_length=70, verbose_name='Titre SEO')),
                ('meta_description', models.CharField(blank=True, help_text='Description meta (≤ 180 caractères).', max_length=180, verbose_name='Description SEO')),
                ('og_image', models.TextField(blank=True, help_text='Image Open Graph (1200×630 recommandé).', max_length=100, null=True, verbose_name='Image Open Graph')),
                ('canonical_url', models.URLField(blank=True, help_text='URL canonique (si le contenu est syndiqué depuis une autre source).', verbose_name='URL canonique')),
                ('mission', models.TextField(blank=True, help_text='Ce que LTL·TV cherche à accomplir au quotidien.', verbose_name='Mission')),
                ('vision', models.TextField(blank=True, help_text='Où LTL·TV se projette à long terme.', verbose_name='Vision')),
                ('history_text', models.TextField(blank=True, help_text="Le récit de la création et de l'évolution de la chaîne.", verbose_name='Histoire')),
                ('founded_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Année de création')),
                ('cover', models.TextField(blank=True, help_text='Bannière affichée en tête de la page « À propos ».', max_length=100, null=True, verbose_name='Image de couverture')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Page « À propos »',
                'verbose_name_plural': 'historical Page « À propos »',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalTeamMember',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Modifié le')),
                ('full_name', models.CharField(max_length=150, verbose_name='Nom complet')),
                ('role', models.CharField(blank=True, help_text='Ex : « Directeur général », « Coordinatrice des programmes ».', max_length=150, verbose_name='Fonction')),
                ('category', models.CharField(choices=[('direction', 'Direction'), ('coordination', 'Coordination'), ('pastorale', 'Équipe pastorale'), ('production', 'Production & réalisation'), ('technique', 'Technique'), ('communication', 'Communication & réseaux sociaux'), ('benevole', 'Bénévole')], db_index=True, default='direction', max_length=20, verbose_name='Catégorie')),
                ('bio', models.TextField(blank=True, verbose_name='Biographie')),
                ('photo', models.TextField(blank=True, max_length=100, null=True, verbose_name='Photo')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email public')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='Téléphone public')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram')),
                ('twitter_url', models.URLField(blank=True, verbose_name='X (Twitter)')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('youtube_url', models.URLField(blank=True, verbose_name='YouTube')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Décochez pour masquer ce membre sans le supprimer.', verbose_name='Actif')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name="Ordre d'affichage")),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "historical Membre de l'équipe",
                'verbose_name_plural': "historical Membres de l'équipe",
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('full_name', models.CharField(max_length=150, verbose_name='Nom complet')),
                ('role', models.CharField(blank=True, help_text='Ex : « Directeur général », « Coordinatrice des programmes ».', max_length=150, verbose_name='Fonction')),
                ('category', models.CharField(choices=[('direction', 'Direction'), ('coordination', 'Coordination'), ('pastorale', 'Équipe pastorale'), ('production', 'Production & réalisation'), ('technique', 'Technique'), ('communication', 'Communication & réseaux sociaux'), ('benevole', 'Bénévole')], db_index=True, default='direction', max_length=20, verbose_name='Catégorie')),
                ('bio', models.TextField(blank=True, verbose_name='Biographie')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='about/team/', verbose_name='Photo')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email public')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='Téléphone public')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram')),
                ('twitter_url', models.URLField(blank=True, verbose_name='X (Twitter)')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('youtube_url', models.URLField(blank=True, verbose_name='YouTube')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Décochez pour masquer ce membre sans le supprimer.', verbose_name='Actif')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': "Membre de l'équipe",
                'verbose_name_plural': "Membres de l'équipe",
                'ordering': ['category', 'order', 'full_name'],
                'indexes': [models.Index(fields=['category', 'is_active'], name='about_teamm_categor_7bc019_idx')],
            },
        ),
    ]
