# Generated by Django 5.0.7 on 2026-08-02 09:18

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='Slug')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('subtitle', models.CharField(blank=True, help_text='Ex. « Live Zoom Meeting Conference (Inscription obligatoire) ».', max_length=200, verbose_name='Sous-titre')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(blank=True, help_text="Vide si l'événement se déroule sur une seule journée.", null=True, verbose_name='Date de fin')),
                ('daily_time', models.TimeField(blank=True, help_text="Heure quotidienne de l'événement (ex : 20:45).", null=True, verbose_name='Heure')),
                ('meeting_url', models.URLField(blank=True, help_text='Lien Zoom / autre, communiqué aux inscrits (usage interne pour le moment).', verbose_name='Lien de la réunion')),
                ('conditions', models.TextField(blank=True, help_text="Affiché sur le formulaire d'inscription, avec un « Voir plus ».", verbose_name='Conditions de participation')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text="Désactive la page et l'inscription si décoché.", verbose_name='Actif')),
                ('is_registration_open', models.BooleanField(db_index=True, default=True, help_text='Permet de fermer les inscriptions sans masquer la page.', verbose_name='Inscriptions ouvertes')),
            ],
            options={
                'verbose_name': 'Événement',
                'verbose_name_plural': 'Événements',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalEvent',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Modifié le')),
                ('slug', models.SlugField(blank=True, max_length=220, verbose_name='Slug')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('subtitle', models.CharField(blank=True, help_text='Ex. « Live Zoom Meeting Conference (Inscription obligatoire) ».', max_length=200, verbose_name='Sous-titre')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(blank=True, help_text="Vide si l'événement se déroule sur une seule journée.", null=True, verbose_name='Date de fin')),
                ('daily_time', models.TimeField(blank=True, help_text="Heure quotidienne de l'événement (ex : 20:45).", null=True, verbose_name='Heure')),
                ('meeting_url', models.URLField(blank=True, help_text='Lien Zoom / autre, communiqué aux inscrits (usage interne pour le moment).', verbose_name='Lien de la réunion')),
                ('conditions', models.TextField(blank=True, help_text="Affiché sur le formulaire d'inscription, avec un « Voir plus ».", verbose_name='Conditions de participation')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text="Désactive la page et l'inscription si décoché.", verbose_name='Actif')),
                ('is_registration_open', models.BooleanField(db_index=True, default=True, help_text='Permet de fermer les inscriptions sans masquer la page.', verbose_name='Inscriptions ouvertes')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Événement',
                'verbose_name_plural': 'historical Événements',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalEventRegistration',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Modifié le')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('gender', models.CharField(max_length=30, verbose_name='Genre')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=32, verbose_name='Téléphone')),
                ('country', models.CharField(blank=True, max_length=80, verbose_name='Pays')),
                ('motivation', models.TextField(help_text='Ce qui motive la personne à participer.', verbose_name='Motivation')),
                ('accepted_conditions', models.BooleanField(default=False, verbose_name='Conditions acceptées')),
                ('internal_notes', models.TextField(blank=True, help_text="Notes de l'équipe. Non visibles par l'inscrit.", verbose_name='Notes internes')),
                ('submitted_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('submitted_user_agent', models.CharField(blank=True, max_length=280, verbose_name='Navigateur')),
                ('referrer', models.URLField(blank=True, verbose_name="Page d'origine")),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('event', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='events.event', verbose_name='Événement')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Inscription',
                'verbose_name_plural': 'historical Inscriptions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('gender', models.CharField(max_length=30, verbose_name='Genre')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=32, verbose_name='Téléphone')),
                ('country', models.CharField(blank=True, max_length=80, verbose_name='Pays')),
                ('motivation', models.TextField(help_text='Ce qui motive la personne à participer.', verbose_name='Motivation')),
                ('accepted_conditions', models.BooleanField(default=False, verbose_name='Conditions acceptées')),
                ('internal_notes', models.TextField(blank=True, help_text="Notes de l'équipe. Non visibles par l'inscrit.", verbose_name='Notes internes')),
                ('submitted_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('submitted_user_agent', models.CharField(blank=True, max_length=280, verbose_name='Navigateur')),
                ('referrer', models.URLField(blank=True, verbose_name="Page d'origine")),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='events.event', verbose_name='Événement')),
            ],
            options={
                'verbose_name': 'Inscription',
                'verbose_name_plural': 'Inscriptions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event', '-created_at'], name='events_even_event_i_d645ce_idx')],
                'unique_together': {('event', 'email')},
            },
        ),
    ]
