# Generated by Django 5.0.7 on 2026-07-06 15:03

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField()),
                ('is_sent', models.BooleanField(db_index=True, default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Réponse',
                'verbose_name_plural': 'Réponses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalContactMessage',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField()),
                ('category', models.CharField(choices=[('question', 'Question'), ('prayer', 'Demande de prière'), ('donation', 'Don'), ('partnership', 'Partenariat'), ('technical', 'Question technique'), ('feedback', 'Feedback / suggestion'), ('other', 'Autre')], db_index=True, default='other', max_length=16)),
                ('priority', models.CharField(choices=[('low', 'Basse'), ('normal', 'Normale'), ('high', 'Haute'), ('urgent', 'Urgente')], db_index=True, default='normal', max_length=16)),
                ('status', models.CharField(choices=[('new', 'Nouveau'), ('read', 'Lu'), ('in_progress', 'En traitement'), ('handled', 'Traité'), ('archived', 'Archivé'), ('spam', 'Spam')], db_index=True, default='new', max_length=16)),
                ('internal_notes', models.TextField(blank=True, help_text='Notes internes non visibles publiquement (scratchpad équipe).')),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('handled_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('submitted_user_agent', models.CharField(blank=True, max_length=280)),
                ('referrer', models.URLField(blank=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Message de contact',
                'verbose_name_plural': 'historical Messages de contact',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Message de contact', 'verbose_name_plural': 'Messages de contact'},
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='is_handled',
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_contacts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='category',
            field=models.CharField(choices=[('question', 'Question'), ('prayer', 'Demande de prière'), ('donation', 'Don'), ('partnership', 'Partenariat'), ('technical', 'Question technique'), ('feedback', 'Feedback / suggestion'), ('other', 'Autre')], db_index=True, default='other', max_length=16),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='handled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='handled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_contacts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='internal_notes',
            field=models.TextField(blank=True, help_text='Notes internes non visibles publiquement (scratchpad équipe).'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='priority',
            field=models.CharField(choices=[('low', 'Basse'), ('normal', 'Normale'), ('high', 'Haute'), ('urgent', 'Urgente')], db_index=True, default='normal', max_length=16),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='referrer',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='status',
            field=models.CharField(choices=[('new', 'Nouveau'), ('read', 'Lu'), ('in_progress', 'En traitement'), ('handled', 'Traité'), ('archived', 'Archivé'), ('spam', 'Spam')], db_index=True, default='new', max_length=16),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='submitted_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='submitted_user_agent',
            field=models.CharField(blank=True, max_length=280),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='contactmessage',
            index=models.Index(fields=['status', 'priority'], name='contacts_co_status_f0a4f0_idx'),
        ),
        migrations.AddIndex(
            model_name='contactmessage',
            index=models.Index(fields=['status', '-created_at'], name='contacts_co_status_ac3bb4_idx'),
        ),
        migrations.AddIndex(
            model_name='contactmessage',
            index=models.Index(fields=['category'], name='contacts_co_categor_a8eca8_idx'),
        ),
        migrations.AddField(
            model_name='contactreply',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_replies_written', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contactreply',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='contacts.contactmessage'),
        ),
        migrations.AddField(
            model_name='historicalcontactmessage',
            name='assigned_to',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcontactmessage',
            name='handled_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcontactmessage',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
