# Generated by Django 5.0.7 on 2026-07-10 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_workflow_categories_replies_audit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text="Membre de l'équipe responsable du traitement.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_contacts', to=settings.AUTH_USER_MODEL, verbose_name='Assigné à'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='category',
            field=models.CharField(choices=[('question', 'Question'), ('prayer', 'Demande de prière'), ('donation', 'Don'), ('partnership', 'Partenariat'), ('technical', 'Question technique'), ('feedback', 'Feedback / suggestion'), ('other', 'Autre')], db_index=True, default='other', help_text='Type de message pour aider au tri.', max_length=16, verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='handled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Traité le'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='handled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_contacts', to=settings.AUTH_USER_MODEL, verbose_name='Traité par'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='internal_notes',
            field=models.TextField(blank=True, help_text="Notes de l'équipe. Non visibles par l'expéditeur.", verbose_name='Notes internes'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='message',
            field=models.TextField(verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(blank=True, max_length=32, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='priority',
            field=models.CharField(choices=[('low', 'Basse'), ('normal', 'Normale'), ('high', 'Haute'), ('urgent', 'Urgente')], db_index=True, default='normal', max_length=16, verbose_name='Priorité'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Lu le'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='referrer',
            field=models.URLField(blank=True, verbose_name="Page d'origine"),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='status',
            field=models.CharField(choices=[('new', 'Nouveau'), ('read', 'Lu'), ('in_progress', 'En traitement'), ('handled', 'Traité'), ('archived', 'Archivé'), ('spam', 'Spam')], db_index=True, default='new', max_length=16, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(blank=True, max_length=200, verbose_name='Sujet'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='submitted_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='submitted_user_agent',
            field=models.CharField(blank=True, max_length=280, verbose_name='Navigateur'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Modifié le'),
        ),
        migrations.AlterField(
            model_name='contactreply',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='contactreply',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Modifié le'),
        ),
        migrations.AlterField(
            model_name='historicalcontactmessage',
            name='assigned_to',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text="Membre de l'équipe responsable du traitement.", null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Assigné à'),
        ),
        migrations.AlterField(
            model_name='historicalcontactmessage',
            name='category',
            field=models.CharField(choices=[('question', 'Question'), ('prayer', 'Demande de prière'), ('donation', 'Don'), ('partnership', 'Partenariat'), ('technical', 'Question technique'), ('feedback', 'Feedback / suggestion'), ('other', 'Autre')], db_index=True, default='other', help_text='Type de message pour aider au tri.', max_length=16, verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='historicalcontactmessage',
            name='created_at',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='historicalcontactmessage',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='historicalcontactmessage',
            name='handled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Traité le'),
        ),
        migrations.AlterField(
            model_name='historicalcontactmessage',
            name='handled_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Traité par'),
        ),
        migrations.AlterField(
            model_name='historicalcontactmessage',
            name='internal_notes',
            field=models.TextField(blank=True, help_text="Notes de l'équipe. Non visibles par l'expéditeur.", verbose_name='Notes internes'),
        ),
        migrations.AlterField(
            model_name='historicalcontactmessage',
            name='message',
            field=models.TextField(verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='historicalcontactmessage',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='historicalcontactmessage',
            name='phone',
            field=models.CharField(blank=True, max_length=32, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='historicalcontactmessage',
            name='priority',
            field=models.CharField(choices=[('low', 'Basse'), ('normal', 'Normale'), ('high', 'Haute'), ('urgent', 'Urgente')], db_index=True, default='normal', max_length=16, verbose_name='Priorité'),
        ),
        migrations.AlterField(
            model_name='historicalcontactmessage',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Lu le'),
        ),
        migrations.AlterField(
            model_name='historicalcontactmessage',
            name='referrer',
            field=models.URLField(blank=True, verbose_name="Page d'origine"),
        ),
        migrations.AlterField(
            model_name='historicalcontactmessage',
            name='status',
            field=models.CharField(choices=[('new', 'Nouveau'), ('read', 'Lu'), ('in_progress', 'En traitement'), ('handled', 'Traité'), ('archived', 'Archivé'), ('spam', 'Spam')], db_index=True, default='new', max_length=16, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='historicalcontactmessage',
            name='subject',
            field=models.CharField(blank=True, max_length=200, verbose_name='Sujet'),
        ),
        migrations.AlterField(
            model_name='historicalcontactmessage',
            name='submitted_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP'),
        ),
        migrations.AlterField(
            model_name='historicalcontactmessage',
            name='submitted_user_agent',
            field=models.CharField(blank=True, max_length=280, verbose_name='Navigateur'),
        ),
        migrations.AlterField(
            model_name='historicalcontactmessage',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Modifié le'),
        ),
    ]
