# Generated by Django 5.0.7 on 2026-07-10 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_alter_contactmessage_assigned_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='category',
            field=models.CharField(choices=[('testimony', 'Témoignage'), ('prayer_request', 'Demande de prière'), ('offering', 'Offrande / don'), ('content_proposal', 'Proposition de contenu'), ('biblical_question', 'Question biblique'), ('feedback', 'Feedback sur LTL·TV'), ('other', 'Autre')], db_index=True, default='other', help_text='Type de message pour aider au tri.', max_length=20, verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='historicalcontactmessage',
            name='category',
            field=models.CharField(choices=[('testimony', 'Témoignage'), ('prayer_request', 'Demande de prière'), ('offering', 'Offrande / don'), ('content_proposal', 'Proposition de contenu'), ('biblical_question', 'Question biblique'), ('feedback', 'Feedback sur LTL·TV'), ('other', 'Autre')], db_index=True, default='other', help_text='Type de message pour aider au tri.', max_length=20, verbose_name='Catégorie'),
        ),
    ]
