# Generated by Django 5.0.7 on 2026-07-14 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_remap_category_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='country',
            field=models.CharField(blank=True, help_text="Pays de l'expéditeur (facultatif).", max_length=80, verbose_name='Pays'),
        ),
        migrations.AddField(
            model_name='historicalcontactmessage',
            name='country',
            field=models.CharField(blank=True, help_text="Pays de l'expéditeur (facultatif).", max_length=80, verbose_name='Pays'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='category',
            field=models.CharField(choices=[('testimony', 'Témoignage'), ('prayer_request', 'Demande de prière'), ('content_proposal', 'Proposition de contenu'), ('offer', 'Offre'), ('offering', 'Don'), ('biblical_question', 'Question biblique'), ('feedback', 'Feedback sur LTL·TV'), ('other', 'Autre')], db_index=True, default='other', help_text='Type de message pour aider au tri.', max_length=20, verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='historicalcontactmessage',
            name='category',
            field=models.CharField(choices=[('testimony', 'Témoignage'), ('prayer_request', 'Demande de prière'), ('content_proposal', 'Proposition de contenu'), ('offer', 'Offre'), ('offering', 'Don'), ('biblical_question', 'Question biblique'), ('feedback', 'Feedback sur LTL·TV'), ('other', 'Autre')], db_index=True, default='other', help_text='Type de message pour aider au tri.', max_length=20, verbose_name='Catégorie'),
        ),
    ]
