# Generated by Django 5.0.7 on 2026-07-16 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_contactmessage_country_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactreply',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_replies_written', to=settings.AUTH_USER_MODEL, verbose_name='Auteur'),
        ),
        migrations.AlterField(
            model_name='contactreply',
            name='body',
            field=models.TextField(verbose_name='Texte de la réponse'),
        ),
        migrations.AlterField(
            model_name='contactreply',
            name='is_sent',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Envoyé'),
        ),
        migrations.AlterField(
            model_name='contactreply',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='contacts.contactmessage', verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='contactreply',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Envoyé le'),
        ),
    ]
