# Generated by Django 5.0.7 on 2026-07-06 15:28

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalArticle',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('slug', models.SlugField(blank=True, max_length=220)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publié'), ('archived', 'Archivé')], db_index=True, default='draft', max_length=16)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, help_text='Date de publication (auto-remplie ; peut être future pour programmer).', null=True)),
                ('is_featured', models.BooleanField(db_index=True, default=False, help_text='Mise en avant sur la home / rubriques.')),
                ('meta_title', models.CharField(blank=True, help_text='Titre HTML (≤ 70 caractères). Si vide, `title` est utilisé.', max_length=70)),
                ('meta_description', models.CharField(blank=True, help_text='Description meta (≤ 180 caractères).', max_length=180)),
                ('og_image', models.TextField(blank=True, help_text='Image Open Graph (1200×630 recommandé).', max_length=100, null=True)),
                ('canonical_url', models.URLField(blank=True, help_text='URL canonique (si le contenu est syndiqué depuis une autre source).')),
                ('title', models.CharField(max_length=220)),
                ('subtitle', models.CharField(blank=True, max_length=280)),
                ('excerpt', models.TextField(blank=True, help_text='Résumé pour vignettes / listes. Auto-tronqué depuis `content_md` si vide.')),
                ('content_md', models.TextField(help_text='Contenu en Markdown (source de vérité éditée).')),
                ('content_html', models.TextField(blank=True, editable=False, help_text='HTML rendu depuis `content_md`. Auto-généré à la sauvegarde.')),
                ('reading_time_minutes', models.PositiveIntegerField(default=0, editable=False, help_text='Temps de lecture estimé (200 mots/minute).')),
                ('cover', models.TextField(blank=True, max_length=100, null=True)),
                ('cover_alt', models.CharField(blank=True, max_length=200)),
                ('cover_credit', models.CharField(blank=True, help_text='Crédit photo / illustration.', max_length=200)),
                ('focus_keyword', models.CharField(blank=True, help_text='Mot-clé principal (référence outillage SEO). Non enforced.', max_length=80)),
                ('no_index', models.BooleanField(default=False, help_text='Empêche l\'indexation par les moteurs (`<meta robots="noindex">`).')),
                ('view_count', models.PositiveIntegerField(default=0, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Article',
                'verbose_name_plural': 'historical Articles',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-published_at', '-created_at'], 'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order', 'name'], 'verbose_name': "Catégorie d'article", 'verbose_name_plural': "Catégories d'article"},
        ),
        migrations.RemoveField(
            model_name='article',
            name='content',
        ),
        migrations.RemoveField(
            model_name='article',
            name='is_published',
        ),
        migrations.AddField(
            model_name='article',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='URL canonique (si le contenu est syndiqué depuis une autre source).'),
        ),
        migrations.AddField(
            model_name='article',
            name='content_html',
            field=models.TextField(blank=True, editable=False, help_text='HTML rendu depuis `content_md`. Auto-généré à la sauvegarde.'),
        ),
        migrations.AddField(
            model_name='article',
            name='content_md',
            field=models.TextField(default='', help_text='Contenu en Markdown (source de vérité éditée).'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='cover_alt',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='article',
            name='cover_credit',
            field=models.CharField(blank=True, help_text='Crédit photo / illustration.', max_length=200),
        ),
        migrations.AddField(
            model_name='article',
            name='focus_keyword',
            field=models.CharField(blank=True, help_text='Mot-clé principal (référence outillage SEO). Non enforced.', max_length=80),
        ),
        migrations.AddField(
            model_name='article',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False, help_text='Mise en avant sur la home / rubriques.'),
        ),
        migrations.AddField(
            model_name='article',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Description meta (≤ 180 caractères).', max_length=180),
        ),
        migrations.AddField(
            model_name='article',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Titre HTML (≤ 70 caractères). Si vide, `title` est utilisé.', max_length=70),
        ),
        migrations.AddField(
            model_name='article',
            name='no_index',
            field=models.BooleanField(default=False, help_text='Empêche l\'indexation par les moteurs (`<meta robots="noindex">`).'),
        ),
        migrations.AddField(
            model_name='article',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Image Open Graph (1200×630 recommandé).', null=True, upload_to='seo/og/'),
        ),
        migrations.AddField(
            model_name='article',
            name='reading_time_minutes',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Temps de lecture estimé (200 mots/minute).'),
        ),
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publié'), ('archived', 'Archivé')], db_index=True, default='draft', max_length=16),
        ),
        migrations.AddField(
            model_name='article',
            name='subtitle',
            field=models.CharField(blank=True, max_length=280),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='article',
            name='view_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(blank=True, default='#3D53EA', max_length=9),
        ),
        migrations.AddField(
            model_name='category',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='articles/categories/'),
        ),
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(blank=True, max_length=280),
        ),
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, help_text="Nom d'icône lucide-react (ex : ``book-open``).", max_length=48),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_description',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_title',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='excerpt',
            field=models.TextField(blank=True, help_text='Résumé pour vignettes / listes. Auto-tronqué depuis `content_md` si vide.'),
        ),
        migrations.AlterField(
            model_name='article',
            name='published_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Date de publication (auto-remplie ; peut être future pour programmer).', null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=220),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, unique=True),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['status', 'published_at'], name='articles_ar_status_7759bd_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['is_featured', 'status'], name='articles_ar_is_feat_cc188d_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['category', 'status'], name='articles_ar_categor_961ad7_idx'),
        ),
        migrations.AddField(
            model_name='historicalarticle',
            name='author',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalarticle',
            name='category',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='articles.category'),
        ),
        migrations.AddField(
            model_name='historicalarticle',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
