# Generated by Django 5.0.7 on 2026-07-10 17:16

import django.db.models.deletion
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_cms_refactor'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='Auteur'),
        ),
        migrations.AlterField(
            model_name='article',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='URL canonique (si le contenu est syndiqué depuis une autre source).', verbose_name='URL canonique'),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='articles.category', verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content_html',
            field=models.TextField(blank=True, editable=False, help_text='HTML rendu depuis le Markdown. Auto-généré à la sauvegarde.', verbose_name='Contenu HTML (auto)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content_md',
            field=models.TextField(help_text='Rédigez votre article en Markdown. Le HTML est généré automatiquement.', verbose_name='Contenu (Markdown)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='articles/', verbose_name='Image de couverture'),
        ),
        migrations.AlterField(
            model_name='article',
            name='cover_alt',
            field=models.CharField(blank=True, help_text="Texte alternatif pour les lecteurs d'écran (accessibilité).", max_length=200, verbose_name='Description de la couverture'),
        ),
        migrations.AlterField(
            model_name='article',
            name='cover_credit',
            field=models.CharField(blank=True, help_text="Crédit du photographe ou de l'illustrateur.", max_length=200, verbose_name='Crédit photo'),
        ),
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='article',
            name='excerpt',
            field=models.TextField(blank=True, help_text='Court résumé affiché sur les vignettes. Auto-généré depuis le contenu si laissé vide.', verbose_name='Résumé'),
        ),
        migrations.AlterField(
            model_name='article',
            name='focus_keyword',
            field=models.CharField(blank=True, help_text='Mot-clé cible pour le référencement.', max_length=80, verbose_name='Mot-clé principal (SEO)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False, help_text='Mise en avant sur la home / rubriques.', verbose_name='Mis en avant'),
        ),
        migrations.AlterField(
            model_name='article',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Description meta (≤ 180 caractères).', max_length=180, verbose_name='Description SEO'),
        ),
        migrations.AlterField(
            model_name='article',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Titre HTML (≤ 70 caractères). Si vide, `title` est utilisé.', max_length=70, verbose_name='Titre SEO'),
        ),
        migrations.AlterField(
            model_name='article',
            name='no_index',
            field=models.BooleanField(default=False, help_text="Cochez pour empêcher l'indexation par Google et autres moteurs.", verbose_name='Ne pas indexer'),
        ),
        migrations.AlterField(
            model_name='article',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Image Open Graph (1200×630 recommandé).', null=True, upload_to='seo/og/', verbose_name='Image Open Graph'),
        ),
        migrations.AlterField(
            model_name='article',
            name='published_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Date de publication (auto-remplie ; peut être future pour programmer).', null=True, verbose_name='Publié le'),
        ),
        migrations.AlterField(
            model_name='article',
            name='reading_time_minutes',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Estimé sur la base de 200 mots par minute.', verbose_name='Temps de lecture (min)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publié'), ('archived', 'Archivé')], db_index=True, default='draft', max_length=16, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='article',
            name='subtitle',
            field=models.CharField(blank=True, max_length=280, verbose_name='Sous-titre'),
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Mots-clés'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=220, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='article',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Modifié le'),
        ),
        migrations.AlterField(
            model_name='article',
            name='view_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Nombre de vues'),
        ),
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(blank=True, default='#3D53EA', max_length=9, verbose_name='Couleur (hex)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='articles/categories/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(blank=True, max_length=280, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, help_text="Nom d'icône lucide-react (ex : book-open, church, tv).", max_length=48, verbose_name='Icône'),
        ),
        migrations.AlterField(
            model_name='category',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Résumé affiché sous le titre dans Google (≤ 180 caractères).', max_length=180, verbose_name='Description SEO'),
        ),
        migrations.AlterField(
            model_name='category',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Titre affiché dans les résultats Google (≤ 70 caractères).', max_length=70, verbose_name='Titre SEO'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=80, unique=True, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='category',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name="Ordre d'affichage"),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Modifié le'),
        ),
        migrations.AlterField(
            model_name='historicalarticle',
            name='author',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Auteur'),
        ),
        migrations.AlterField(
            model_name='historicalarticle',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='URL canonique (si le contenu est syndiqué depuis une autre source).', verbose_name='URL canonique'),
        ),
        migrations.AlterField(
            model_name='historicalarticle',
            name='category',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='articles.category', verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='historicalarticle',
            name='content_html',
            field=models.TextField(blank=True, editable=False, help_text='HTML rendu depuis le Markdown. Auto-généré à la sauvegarde.', verbose_name='Contenu HTML (auto)'),
        ),
        migrations.AlterField(
            model_name='historicalarticle',
            name='content_md',
            field=models.TextField(help_text='Rédigez votre article en Markdown. Le HTML est généré automatiquement.', verbose_name='Contenu (Markdown)'),
        ),
        migrations.AlterField(
            model_name='historicalarticle',
            name='cover',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Image de couverture'),
        ),
        migrations.AlterField(
            model_name='historicalarticle',
            name='cover_alt',
            field=models.CharField(blank=True, help_text="Texte alternatif pour les lecteurs d'écran (accessibilité).", max_length=200, verbose_name='Description de la couverture'),
        ),
        migrations.AlterField(
            model_name='historicalarticle',
            name='cover_credit',
            field=models.CharField(blank=True, help_text="Crédit du photographe ou de l'illustrateur.", max_length=200, verbose_name='Crédit photo'),
        ),
        migrations.AlterField(
            model_name='historicalarticle',
            name='created_at',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='historicalarticle',
            name='excerpt',
            field=models.TextField(blank=True, help_text='Court résumé affiché sur les vignettes. Auto-généré depuis le contenu si laissé vide.', verbose_name='Résumé'),
        ),
        migrations.AlterField(
            model_name='historicalarticle',
            name='focus_keyword',
            field=models.CharField(blank=True, help_text='Mot-clé cible pour le référencement.', max_length=80, verbose_name='Mot-clé principal (SEO)'),
        ),
        migrations.AlterField(
            model_name='historicalarticle',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False, help_text='Mise en avant sur la home / rubriques.', verbose_name='Mis en avant'),
        ),
        migrations.AlterField(
            model_name='historicalarticle',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Description meta (≤ 180 caractères).', max_length=180, verbose_name='Description SEO'),
        ),
        migrations.AlterField(
            model_name='historicalarticle',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Titre HTML (≤ 70 caractères). Si vide, `title` est utilisé.', max_length=70, verbose_name='Titre SEO'),
        ),
        migrations.AlterField(
            model_name='historicalarticle',
            name='no_index',
            field=models.BooleanField(default=False, help_text="Cochez pour empêcher l'indexation par Google et autres moteurs.", verbose_name='Ne pas indexer'),
        ),
        migrations.AlterField(
            model_name='historicalarticle',
            name='og_image',
            field=models.TextField(blank=True, help_text='Image Open Graph (1200×630 recommandé).', max_length=100, null=True, verbose_name='Image Open Graph'),
        ),
        migrations.AlterField(
            model_name='historicalarticle',
            name='published_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Date de publication (auto-remplie ; peut être future pour programmer).', null=True, verbose_name='Publié le'),
        ),
        migrations.AlterField(
            model_name='historicalarticle',
            name='reading_time_minutes',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Estimé sur la base de 200 mots par minute.', verbose_name='Temps de lecture (min)'),
        ),
        migrations.AlterField(
            model_name='historicalarticle',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='historicalarticle',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publié'), ('archived', 'Archivé')], db_index=True, default='draft', max_length=16, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='historicalarticle',
            name='subtitle',
            field=models.CharField(blank=True, max_length=280, verbose_name='Sous-titre'),
        ),
        migrations.AlterField(
            model_name='historicalarticle',
            name='title',
            field=models.CharField(max_length=220, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='historicalarticle',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Modifié le'),
        ),
        migrations.AlterField(
            model_name='historicalarticle',
            name='view_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Nombre de vues'),
        ),
    ]
