# Generated by Django 5.0.7 on 2026-07-16 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_article_author_alter_article_canonical_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='À remplir seulement si ce contenu existe déjà ailleurs sur un autre site internet. Dans la plupart des cas, laissez ce champ vide.', verbose_name='Lien vers la version originale'),
        ),
        migrations.AlterField(
            model_name='article',
            name='focus_keyword',
            field=models.CharField(blank=True, help_text="Le mot ou l'expression que les gens pourraient taper dans Google pour trouver cet article. Optionnel.", max_length=80, verbose_name='Mot-clé principal pour Google'),
        ),
        migrations.AlterField(
            model_name='article',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Le résumé qui apparaît sous le titre dans les résultats Google (180 caractères max).', max_length=180, verbose_name='Description affichée dans Google'),
        ),
        migrations.AlterField(
            model_name='article',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Le titre qui apparaît dans les résultats de recherche Google (70 caractères max). Laissez vide pour utiliser le titre normal de la page.', max_length=70, verbose_name='Titre affiché dans Google'),
        ),
        migrations.AlterField(
            model_name='article',
            name='no_index',
            field=models.BooleanField(default=False, help_text="Cochez pour empêcher Google et les autres moteurs de recherche d'afficher cette page.", verbose_name='Cacher cette page à Google'),
        ),
        migrations.AlterField(
            model_name='article',
            name='og_image',
            field=models.ImageField(blank=True, help_text="L'image qui s'affiche quand cette page est partagée sur Facebook, WhatsApp, etc. (1200×630 pixels recommandé).", null=True, upload_to='seo/og/', verbose_name='Image de partage'),
        ),
        migrations.AlterField(
            model_name='historicalarticle',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='À remplir seulement si ce contenu existe déjà ailleurs sur un autre site internet. Dans la plupart des cas, laissez ce champ vide.', verbose_name='Lien vers la version originale'),
        ),
        migrations.AlterField(
            model_name='historicalarticle',
            name='focus_keyword',
            field=models.CharField(blank=True, help_text="Le mot ou l'expression que les gens pourraient taper dans Google pour trouver cet article. Optionnel.", max_length=80, verbose_name='Mot-clé principal pour Google'),
        ),
        migrations.AlterField(
            model_name='historicalarticle',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Le résumé qui apparaît sous le titre dans les résultats Google (180 caractères max).', max_length=180, verbose_name='Description affichée dans Google'),
        ),
        migrations.AlterField(
            model_name='historicalarticle',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Le titre qui apparaît dans les résultats de recherche Google (70 caractères max). Laissez vide pour utiliser le titre normal de la page.', max_length=70, verbose_name='Titre affiché dans Google'),
        ),
        migrations.AlterField(
            model_name='historicalarticle',
            name='no_index',
            field=models.BooleanField(default=False, help_text="Cochez pour empêcher Google et les autres moteurs de recherche d'afficher cette page.", verbose_name='Cacher cette page à Google'),
        ),
        migrations.AlterField(
            model_name='historicalarticle',
            name='og_image',
            field=models.TextField(blank=True, help_text="L'image qui s'affiche quand cette page est partagée sur Facebook, WhatsApp, etc. (1200×630 pixels recommandé).", max_length=100, null=True, verbose_name='Image de partage'),
        ),
    ]
