# Generated by Django 5.0.7 on 2026-07-16 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_article_canonical_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content_html',
            field=models.TextField(blank=True, editable=False, help_text='Copie du contenu ci-dessus, générée automatiquement à la sauvegarde.', verbose_name='Contenu HTML (auto)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content_md',
            field=models.TextField(help_text="Le corps de l'article.", verbose_name='Contenu'),
        ),
        migrations.AlterField(
            model_name='historicalarticle',
            name='content_html',
            field=models.TextField(blank=True, editable=False, help_text='Copie du contenu ci-dessus, générée automatiquement à la sauvegarde.', verbose_name='Contenu HTML (auto)'),
        ),
        migrations.AlterField(
            model_name='historicalarticle',
            name='content_md',
            field=models.TextField(help_text="Le corps de l'article.", verbose_name='Contenu'),
        ),
    ]
