# Generated by Django 5.0.7 on 2026-07-06 09:03

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalWeeklyProgram',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('slug', models.SlugField(blank=True, max_length=220)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publié'), ('archived', 'Archivé')], db_index=True, default='draft', max_length=16)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, help_text='Date de publication (auto-remplie ; peut être future pour programmer).', null=True)),
                ('is_featured', models.BooleanField(db_index=True, default=False, help_text='Mise en avant sur la home / rubriques.')),
                ('meta_title', models.CharField(blank=True, help_text='Titre HTML (≤ 70 caractères). Si vide, `title` est utilisé.', max_length=70)),
                ('meta_description', models.CharField(blank=True, help_text='Description meta (≤ 180 caractères).', max_length=180)),
                ('og_image', models.TextField(blank=True, help_text='Image Open Graph (1200×630 recommandé).', max_length=100, null=True)),
                ('canonical_url', models.URLField(blank=True, help_text='URL canonique (si le contenu est syndiqué depuis une autre source).')),
                ('date', models.DateField(db_index=True, help_text='Date du programme.')),
                ('start_time', models.TimeField(help_text='Heure de début (fuseau local).')),
                ('end_time', models.TimeField(blank=True, help_text='Heure de fin (optionnelle).', null=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('responsable', models.CharField(blank=True, help_text='Responsable / animateur principal.', max_length=200)),
                ('mode', models.CharField(choices=[('in_person', 'Présentiel'), ('online', 'En ligne'), ('hybrid', 'Hybride')], db_index=True, default='in_person', max_length=16)),
                ('location', models.CharField(blank=True, help_text='Ville / lieu (ex : « Kinshasa — Bandal »).', max_length=200)),
                ('address', models.CharField(blank=True, help_text='Adresse complète (présentiel).', max_length=280)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('meeting_url', models.URLField(blank=True, help_text='Lien Zoom / YouTube / autre (en ligne ou hybride).')),
                ('image', models.TextField(blank=True, help_text='Bannière du programme (16:9 recommandé).', max_length=100, null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text="Ordre au sein d'une même date (utile pour plusieurs programmes le même jour).")),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Programme hebdomadaire',
                'verbose_name_plural': 'historical Programmes hebdomadaires',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ProgramType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('description', models.CharField(blank=True, max_length=280)),
                ('color', models.CharField(blank=True, default='#3D53EA', help_text="Couleur d'accent (hex).", max_length=9)),
                ('icon', models.CharField(blank=True, help_text="Nom d'icône lucide-react (ex : ``church``, ``users``, ``mic``, ``book-open``).", max_length=48)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
            ],
            options={
                'verbose_name': 'Type de programme',
                'verbose_name_plural': 'Types de programme',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publié'), ('archived', 'Archivé')], db_index=True, default='draft', max_length=16)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, help_text='Date de publication (auto-remplie ; peut être future pour programmer).', null=True)),
                ('is_featured', models.BooleanField(db_index=True, default=False, help_text='Mise en avant sur la home / rubriques.')),
                ('meta_title', models.CharField(blank=True, help_text='Titre HTML (≤ 70 caractères). Si vide, `title` est utilisé.', max_length=70)),
                ('meta_description', models.CharField(blank=True, help_text='Description meta (≤ 180 caractères).', max_length=180)),
                ('og_image', models.ImageField(blank=True, help_text='Image Open Graph (1200×630 recommandé).', null=True, upload_to='seo/og/')),
                ('canonical_url', models.URLField(blank=True, help_text='URL canonique (si le contenu est syndiqué depuis une autre source).')),
                ('date', models.DateField(db_index=True, help_text='Date du programme.')),
                ('start_time', models.TimeField(help_text='Heure de début (fuseau local).')),
                ('end_time', models.TimeField(blank=True, help_text='Heure de fin (optionnelle).', null=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('responsable', models.CharField(blank=True, help_text='Responsable / animateur principal.', max_length=200)),
                ('mode', models.CharField(choices=[('in_person', 'Présentiel'), ('online', 'En ligne'), ('hybrid', 'Hybride')], db_index=True, default='in_person', max_length=16)),
                ('location', models.CharField(blank=True, help_text='Ville / lieu (ex : « Kinshasa — Bandal »).', max_length=200)),
                ('address', models.CharField(blank=True, help_text='Adresse complète (présentiel).', max_length=280)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('meeting_url', models.URLField(blank=True, help_text='Lien Zoom / YouTube / autre (en ligne ou hybride).')),
                ('image', models.ImageField(blank=True, help_text='Bannière du programme (16:9 recommandé).', null=True, upload_to='programmes/')),
                ('order', models.PositiveIntegerField(default=0, help_text="Ordre au sein d'une même date (utile pour plusieurs programmes le même jour).")),
                ('program_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='programs', to='programmes.programtype')),
            ],
            options={
                'verbose_name': 'Programme hebdomadaire',
                'verbose_name_plural': 'Programmes hebdomadaires',
                'ordering': ['date', 'start_time', 'order'],
            },
        ),
        migrations.DeleteModel(
            name='Programme',
        ),
        migrations.AddField(
            model_name='historicalweeklyprogram',
            name='program_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='programmes.programtype'),
        ),
        migrations.AddIndex(
            model_name='weeklyprogram',
            index=models.Index(fields=['date', 'start_time'], name='programmes__date_b3fc62_idx'),
        ),
        migrations.AddIndex(
            model_name='weeklyprogram',
            index=models.Index(fields=['status', 'date'], name='programmes__status_b4d934_idx'),
        ),
        migrations.AddIndex(
            model_name='weeklyprogram',
            index=models.Index(fields=['is_featured', 'status'], name='programmes__is_feat_8b210d_idx'),
        ),
    ]
