# Generated by Django 5.0.7 on 2026-07-10 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0003_seed_program_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalweeklyprogram',
            name='address',
            field=models.CharField(blank=True, help_text='Adresse complète (présentiel).', max_length=280, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='historicalweeklyprogram',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='URL canonique (si le contenu est syndiqué depuis une autre source).', verbose_name='URL canonique'),
        ),
        migrations.AlterField(
            model_name='historicalweeklyprogram',
            name='created_at',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='historicalweeklyprogram',
            name='date',
            field=models.DateField(db_index=True, help_text='Date du programme.', verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='historicalweeklyprogram',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='historicalweeklyprogram',
            name='end_time',
            field=models.TimeField(blank=True, help_text='Heure de fin (optionnelle).', null=True, verbose_name='Heure de fin'),
        ),
        migrations.AlterField(
            model_name='historicalweeklyprogram',
            name='image',
            field=models.TextField(blank=True, help_text='Bannière du programme (16:9 recommandé).', max_length=100, null=True, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='historicalweeklyprogram',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False, help_text='Mise en avant sur la home / rubriques.', verbose_name='Mis en avant'),
        ),
        migrations.AlterField(
            model_name='historicalweeklyprogram',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='historicalweeklyprogram',
            name='location',
            field=models.CharField(blank=True, help_text='Ville / lieu (ex : « Kinshasa — Bandal »).', max_length=200, verbose_name='Lieu'),
        ),
        migrations.AlterField(
            model_name='historicalweeklyprogram',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='historicalweeklyprogram',
            name='meeting_url',
            field=models.URLField(blank=True, help_text='Lien Zoom / YouTube / autre (en ligne ou hybride).', verbose_name='Lien de la réunion'),
        ),
        migrations.AlterField(
            model_name='historicalweeklyprogram',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Description meta (≤ 180 caractères).', max_length=180, verbose_name='Description SEO'),
        ),
        migrations.AlterField(
            model_name='historicalweeklyprogram',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Titre HTML (≤ 70 caractères). Si vide, `title` est utilisé.', max_length=70, verbose_name='Titre SEO'),
        ),
        migrations.AlterField(
            model_name='historicalweeklyprogram',
            name='mode',
            field=models.CharField(choices=[('in_person', 'Présentiel'), ('online', 'En ligne'), ('hybrid', 'Hybride')], db_index=True, default='in_person', max_length=16, verbose_name='Mode'),
        ),
        migrations.AlterField(
            model_name='historicalweeklyprogram',
            name='og_image',
            field=models.TextField(blank=True, help_text='Image Open Graph (1200×630 recommandé).', max_length=100, null=True, verbose_name='Image Open Graph'),
        ),
        migrations.AlterField(
            model_name='historicalweeklyprogram',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text="Ordre au sein d'une même date (utile pour plusieurs programmes le même jour).", verbose_name="Ordre d'affichage"),
        ),
        migrations.AlterField(
            model_name='historicalweeklyprogram',
            name='program_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='programmes.programtype', verbose_name='Type de programme'),
        ),
        migrations.AlterField(
            model_name='historicalweeklyprogram',
            name='published_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Date de publication (auto-remplie ; peut être future pour programmer).', null=True, verbose_name='Publié le'),
        ),
        migrations.AlterField(
            model_name='historicalweeklyprogram',
            name='responsable',
            field=models.CharField(blank=True, help_text='Responsable / animateur principal.', max_length=200, verbose_name='Responsable'),
        ),
        migrations.AlterField(
            model_name='historicalweeklyprogram',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='historicalweeklyprogram',
            name='start_time',
            field=models.TimeField(help_text='Heure de début (fuseau local).', verbose_name='Heure de début'),
        ),
        migrations.AlterField(
            model_name='historicalweeklyprogram',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publié'), ('archived', 'Archivé')], db_index=True, default='draft', max_length=16, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='historicalweeklyprogram',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='historicalweeklyprogram',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Modifié le'),
        ),
        migrations.AlterField(
            model_name='programtype',
            name='color',
            field=models.CharField(blank=True, default='#3D53EA', max_length=9, verbose_name='Couleur (hex)'),
        ),
        migrations.AlterField(
            model_name='programtype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='programtype',
            name='description',
            field=models.CharField(blank=True, max_length=280, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='programtype',
            name='icon',
            field=models.CharField(blank=True, help_text="Nom d'icône lucide-react (ex : church, users, mic, book-open).", max_length=48, verbose_name='Icône'),
        ),
        migrations.AlterField(
            model_name='programtype',
            name='name',
            field=models.CharField(max_length=80, unique=True, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='programtype',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name="Ordre d'affichage"),
        ),
        migrations.AlterField(
            model_name='programtype',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='programtype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Modifié le'),
        ),
        migrations.AlterField(
            model_name='weeklyprogram',
            name='address',
            field=models.CharField(blank=True, help_text='Adresse complète (présentiel).', max_length=280, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='weeklyprogram',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='URL canonique (si le contenu est syndiqué depuis une autre source).', verbose_name='URL canonique'),
        ),
        migrations.AlterField(
            model_name='weeklyprogram',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='weeklyprogram',
            name='date',
            field=models.DateField(db_index=True, help_text='Date du programme.', verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='weeklyprogram',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='weeklyprogram',
            name='end_time',
            field=models.TimeField(blank=True, help_text='Heure de fin (optionnelle).', null=True, verbose_name='Heure de fin'),
        ),
        migrations.AlterField(
            model_name='weeklyprogram',
            name='image',
            field=models.ImageField(blank=True, help_text='Bannière du programme (16:9 recommandé).', null=True, upload_to='programmes/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='weeklyprogram',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False, help_text='Mise en avant sur la home / rubriques.', verbose_name='Mis en avant'),
        ),
        migrations.AlterField(
            model_name='weeklyprogram',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='weeklyprogram',
            name='location',
            field=models.CharField(blank=True, help_text='Ville / lieu (ex : « Kinshasa — Bandal »).', max_length=200, verbose_name='Lieu'),
        ),
        migrations.AlterField(
            model_name='weeklyprogram',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='weeklyprogram',
            name='meeting_url',
            field=models.URLField(blank=True, help_text='Lien Zoom / YouTube / autre (en ligne ou hybride).', verbose_name='Lien de la réunion'),
        ),
        migrations.AlterField(
            model_name='weeklyprogram',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Description meta (≤ 180 caractères).', max_length=180, verbose_name='Description SEO'),
        ),
        migrations.AlterField(
            model_name='weeklyprogram',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Titre HTML (≤ 70 caractères). Si vide, `title` est utilisé.', max_length=70, verbose_name='Titre SEO'),
        ),
        migrations.AlterField(
            model_name='weeklyprogram',
            name='mode',
            field=models.CharField(choices=[('in_person', 'Présentiel'), ('online', 'En ligne'), ('hybrid', 'Hybride')], db_index=True, default='in_person', max_length=16, verbose_name='Mode'),
        ),
        migrations.AlterField(
            model_name='weeklyprogram',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Image Open Graph (1200×630 recommandé).', null=True, upload_to='seo/og/', verbose_name='Image Open Graph'),
        ),
        migrations.AlterField(
            model_name='weeklyprogram',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text="Ordre au sein d'une même date (utile pour plusieurs programmes le même jour).", verbose_name="Ordre d'affichage"),
        ),
        migrations.AlterField(
            model_name='weeklyprogram',
            name='program_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='programs', to='programmes.programtype', verbose_name='Type de programme'),
        ),
        migrations.AlterField(
            model_name='weeklyprogram',
            name='published_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Date de publication (auto-remplie ; peut être future pour programmer).', null=True, verbose_name='Publié le'),
        ),
        migrations.AlterField(
            model_name='weeklyprogram',
            name='responsable',
            field=models.CharField(blank=True, help_text='Responsable / animateur principal.', max_length=200, verbose_name='Responsable'),
        ),
        migrations.AlterField(
            model_name='weeklyprogram',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='weeklyprogram',
            name='start_time',
            field=models.TimeField(help_text='Heure de début (fuseau local).', verbose_name='Heure de début'),
        ),
        migrations.AlterField(
            model_name='weeklyprogram',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publié'), ('archived', 'Archivé')], db_index=True, default='draft', max_length=16, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='weeklyprogram',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='weeklyprogram',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Modifié le'),
        ),
    ]
