# Generated by Django 5.0.7 on 2026-07-14 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0004_alter_historicalweeklyprogram_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalweeklyprogram',
            name='youtube_id',
            field=models.CharField(blank=True, db_index=True, help_text="Auto-extrait de l'URL.", max_length=20, verbose_name='ID YouTube'),
        ),
        migrations.AddField(
            model_name='historicalweeklyprogram',
            name='youtube_url',
            field=models.URLField(blank=True, help_text="Lien de la vidéo YouTube associée (optionnel). Sa miniature sert de couverture si aucune image n'est fournie.", verbose_name='URL YouTube'),
        ),
        migrations.AddField(
            model_name='weeklyprogram',
            name='youtube_id',
            field=models.CharField(blank=True, db_index=True, help_text="Auto-extrait de l'URL.", max_length=20, verbose_name='ID YouTube'),
        ),
        migrations.AddField(
            model_name='weeklyprogram',
            name='youtube_url',
            field=models.URLField(blank=True, help_text="Lien de la vidéo YouTube associée (optionnel). Sa miniature sert de couverture si aucune image n'est fournie.", verbose_name='URL YouTube'),
        ),
        migrations.AlterField(
            model_name='historicalweeklyprogram',
            name='image',
            field=models.TextField(blank=True, help_text='Bannière du programme (16:9 recommandé). Laissez vide pour utiliser la miniature de la vidéo YouTube.', max_length=100, null=True, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='weeklyprogram',
            name='image',
            field=models.ImageField(blank=True, help_text='Bannière du programme (16:9 recommandé). Laissez vide pour utiliser la miniature de la vidéo YouTube.', null=True, upload_to='programmes/', verbose_name='Image'),
        ),
    ]
