# Generated by Django 5.0.7 on 2026-07-16 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0005_historicalweeklyprogram_youtube_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalweeklyprogram',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='À remplir seulement si ce contenu existe déjà ailleurs sur un autre site internet. Dans la plupart des cas, laissez ce champ vide.', verbose_name='Lien vers la version originale'),
        ),
        migrations.AlterField(
            model_name='historicalweeklyprogram',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Le résumé qui apparaît sous le titre dans les résultats Google (180 caractères max).', max_length=180, verbose_name='Description affichée dans Google'),
        ),
        migrations.AlterField(
            model_name='historicalweeklyprogram',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Le titre qui apparaît dans les résultats de recherche Google (70 caractères max). Laissez vide pour utiliser le titre normal de la page.', max_length=70, verbose_name='Titre affiché dans Google'),
        ),
        migrations.AlterField(
            model_name='historicalweeklyprogram',
            name='og_image',
            field=models.TextField(blank=True, help_text="L'image qui s'affiche quand cette page est partagée sur Facebook, WhatsApp, etc. (1200×630 pixels recommandé).", max_length=100, null=True, verbose_name='Image de partage'),
        ),
        migrations.AlterField(
            model_name='weeklyprogram',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='À remplir seulement si ce contenu existe déjà ailleurs sur un autre site internet. Dans la plupart des cas, laissez ce champ vide.', verbose_name='Lien vers la version originale'),
        ),
        migrations.AlterField(
            model_name='weeklyprogram',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Le résumé qui apparaît sous le titre dans les résultats Google (180 caractères max).', max_length=180, verbose_name='Description affichée dans Google'),
        ),
        migrations.AlterField(
            model_name='weeklyprogram',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Le titre qui apparaît dans les résultats de recherche Google (70 caractères max). Laissez vide pour utiliser le titre normal de la page.', max_length=70, verbose_name='Titre affiché dans Google'),
        ),
        migrations.AlterField(
            model_name='weeklyprogram',
            name='og_image',
            field=models.ImageField(blank=True, help_text="L'image qui s'affiche quand cette page est partagée sur Facebook, WhatsApp, etc. (1200×630 pixels recommandé).", null=True, upload_to='seo/og/', verbose_name='Image de partage'),
        ),
    ]
