# Generated by Django 5.0.7 on 2026-07-05 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, help_text="Biographie publique (utilisée pour l'affichage des auteurs)."),
        ),
        migrations.AddField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_email_verified', 'is_active'], name='accounts_us_is_emai_d3d27b_idx'),
        ),
    ]
