# Generated by Django 5.0.7 on 2026-07-10 17:16

import django.db.models.deletion
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0002_seed_initial_shows'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(blank=True, default='', help_text="Couleur d'accent (hex, ex : ``#3D53EA``).", max_length=9, verbose_name='Couleur (hex)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(blank=True, max_length=280, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=80, unique=True, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='category',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name="Ordre d'affichage"),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Modifié le'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='aired_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Date/heure de première diffusion.', null=True, verbose_name='Diffusé le'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='URL canonique (si le contenu est syndiqué depuis une autre source).', verbose_name='URL canonique'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='episodes', to='emissions.category', verbose_name='Catégories'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='cover',
            field=models.ImageField(blank=True, help_text='Miniature personnalisée. Si vide, celle de YouTube est utilisée.', null=True, upload_to='emissions/episodes/cover/', verbose_name='Miniature'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='description',
            field=models.TextField(blank=True, help_text='Notes / plan / commentaire long.', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='duration_seconds',
            field=models.PositiveIntegerField(default=0, help_text='Durée en secondes. 0 = inconnue.', verbose_name='Durée (secondes)'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='excerpt',
            field=models.TextField(blank=True, help_text='Résumé court (2-3 phrases).', verbose_name='Résumé'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='guests',
            field=models.JSONField(blank=True, default=list, help_text='Invités additionnels : liste de dicts ``[{"name": "...", "role": "..."}]``.', verbose_name='Invités'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False, help_text='Mise en avant sur la home / rubriques.', verbose_name='Mis en avant'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Description meta (≤ 180 caractères).', max_length=180, verbose_name='Description SEO'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Titre HTML (≤ 70 caractères). Si vide, `title` est utilisé.', max_length=70, verbose_name='Titre SEO'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Image Open Graph (1200×630 recommandé).', null=True, upload_to='seo/og/', verbose_name='Image Open Graph'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='published_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Date de publication (auto-remplie ; peut être future pour programmer).', null=True, verbose_name='Publié le'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='emissions.show', verbose_name='Émission'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='speaker',
            field=models.CharField(blank=True, help_text="Nom de l'intervenant principal.", max_length=200, verbose_name='Intervenant'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publié'), ('archived', 'Archivé')], db_index=True, default='draft', max_length=16, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='subtitle',
            field=models.CharField(blank=True, max_length=280, verbose_name='Sous-titre'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Mots-clés'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='title',
            field=models.CharField(max_length=220, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Modifié le'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='view_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Nombre de vues'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='youtube_id',
            field=models.CharField(blank=True, db_index=True, help_text="Auto-extrait de l'URL. Utilisé pour l'embed et la miniature.", max_length=20, verbose_name='ID YouTube'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='youtube_url',
            field=models.URLField(help_text='URL YouTube (formats : watch, youtu.be, shorts, live, embed).', verbose_name='URL YouTube'),
        ),
        migrations.AlterField(
            model_name='historicalepisode',
            name='aired_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Date/heure de première diffusion.', null=True, verbose_name='Diffusé le'),
        ),
        migrations.AlterField(
            model_name='historicalepisode',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='URL canonique (si le contenu est syndiqué depuis une autre source).', verbose_name='URL canonique'),
        ),
        migrations.AlterField(
            model_name='historicalepisode',
            name='cover',
            field=models.TextField(blank=True, help_text='Miniature personnalisée. Si vide, celle de YouTube est utilisée.', max_length=100, null=True, verbose_name='Miniature'),
        ),
        migrations.AlterField(
            model_name='historicalepisode',
            name='created_at',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='historicalepisode',
            name='description',
            field=models.TextField(blank=True, help_text='Notes / plan / commentaire long.', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='historicalepisode',
            name='duration_seconds',
            field=models.PositiveIntegerField(default=0, help_text='Durée en secondes. 0 = inconnue.', verbose_name='Durée (secondes)'),
        ),
        migrations.AlterField(
            model_name='historicalepisode',
            name='excerpt',
            field=models.TextField(blank=True, help_text='Résumé court (2-3 phrases).', verbose_name='Résumé'),
        ),
        migrations.AlterField(
            model_name='historicalepisode',
            name='guests',
            field=models.JSONField(blank=True, default=list, help_text='Invités additionnels : liste de dicts ``[{"name": "...", "role": "..."}]``.', verbose_name='Invités'),
        ),
        migrations.AlterField(
            model_name='historicalepisode',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False, help_text='Mise en avant sur la home / rubriques.', verbose_name='Mis en avant'),
        ),
        migrations.AlterField(
            model_name='historicalepisode',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Description meta (≤ 180 caractères).', max_length=180, verbose_name='Description SEO'),
        ),
        migrations.AlterField(
            model_name='historicalepisode',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Titre HTML (≤ 70 caractères). Si vide, `title` est utilisé.', max_length=70, verbose_name='Titre SEO'),
        ),
        migrations.AlterField(
            model_name='historicalepisode',
            name='og_image',
            field=models.TextField(blank=True, help_text='Image Open Graph (1200×630 recommandé).', max_length=100, null=True, verbose_name='Image Open Graph'),
        ),
        migrations.AlterField(
            model_name='historicalepisode',
            name='published_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Date de publication (auto-remplie ; peut être future pour programmer).', null=True, verbose_name='Publié le'),
        ),
        migrations.AlterField(
            model_name='historicalepisode',
            name='show',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='emissions.show', verbose_name='Émission'),
        ),
        migrations.AlterField(
            model_name='historicalepisode',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='historicalepisode',
            name='speaker',
            field=models.CharField(blank=True, help_text="Nom de l'intervenant principal.", max_length=200, verbose_name='Intervenant'),
        ),
        migrations.AlterField(
            model_name='historicalepisode',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publié'), ('archived', 'Archivé')], db_index=True, default='draft', max_length=16, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='historicalepisode',
            name='subtitle',
            field=models.CharField(blank=True, max_length=280, verbose_name='Sous-titre'),
        ),
        migrations.AlterField(
            model_name='historicalepisode',
            name='title',
            field=models.CharField(max_length=220, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='historicalepisode',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Modifié le'),
        ),
        migrations.AlterField(
            model_name='historicalepisode',
            name='view_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Nombre de vues'),
        ),
        migrations.AlterField(
            model_name='historicalepisode',
            name='youtube_id',
            field=models.CharField(blank=True, db_index=True, help_text="Auto-extrait de l'URL. Utilisé pour l'embed et la miniature.", max_length=20, verbose_name='ID YouTube'),
        ),
        migrations.AlterField(
            model_name='historicalepisode',
            name='youtube_url',
            field=models.URLField(help_text='URL YouTube (formats : watch, youtu.be, shorts, live, embed).', verbose_name='URL YouTube'),
        ),
        migrations.AlterField(
            model_name='historicalshow',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='URL canonique (si le contenu est syndiqué depuis une autre source).', verbose_name='URL canonique'),
        ),
        migrations.AlterField(
            model_name='historicalshow',
            name='color',
            field=models.CharField(blank=True, default='#3D53EA', help_text="Couleur d'accent (hex).", max_length=9, verbose_name='Couleur (hex)'),
        ),
        migrations.AlterField(
            model_name='historicalshow',
            name='cover',
            field=models.TextField(blank=True, help_text='Bannière large (16:9 recommandé).', max_length=100, null=True, verbose_name='Image de couverture'),
        ),
        migrations.AlterField(
            model_name='historicalshow',
            name='created_at',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='historicalshow',
            name='default_schedule',
            field=models.CharField(blank=True, help_text='Ex : « Lundi — Vendredi · 07h00 » (texte libre).', max_length=200, verbose_name='Horaire habituel'),
        ),
        migrations.AlterField(
            model_name='historicalshow',
            name='description',
            field=models.TextField(blank=True, help_text="Description longue de l'émission (page dédiée).", verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='historicalshow',
            name='host',
            field=models.CharField(blank=True, help_text='Animateur / pasteur principal.', max_length=200, verbose_name='Animateur'),
        ),
        migrations.AlterField(
            model_name='historicalshow',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False, help_text='Mise en avant sur la home / rubriques.', verbose_name='Mis en avant'),
        ),
        migrations.AlterField(
            model_name='historicalshow',
            name='logo',
            field=models.TextField(blank=True, help_text='Logo transparent (carte, footer).', max_length=100, null=True, verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='historicalshow',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Description meta (≤ 180 caractères).', max_length=180, verbose_name='Description SEO'),
        ),
        migrations.AlterField(
            model_name='historicalshow',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Titre HTML (≤ 70 caractères). Si vide, `title` est utilisé.', max_length=70, verbose_name='Titre SEO'),
        ),
        migrations.AlterField(
            model_name='historicalshow',
            name='og_image',
            field=models.TextField(blank=True, help_text='Image Open Graph (1200×630 recommandé).', max_length=100, null=True, verbose_name='Image Open Graph'),
        ),
        migrations.AlterField(
            model_name='historicalshow',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text="Ordre d'affichage (plus petit = plus en avant).", verbose_name="Ordre d'affichage"),
        ),
        migrations.AlterField(
            model_name='historicalshow',
            name='published_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Date de publication (auto-remplie ; peut être future pour programmer).', null=True, verbose_name='Publié le'),
        ),
        migrations.AlterField(
            model_name='historicalshow',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='historicalshow',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publié'), ('archived', 'Archivé')], db_index=True, default='draft', max_length=16, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='historicalshow',
            name='tagline',
            field=models.CharField(blank=True, help_text='Court résumé, utilisé dans les cartes et vignettes.', max_length=280, verbose_name='Accroche'),
        ),
        migrations.AlterField(
            model_name='historicalshow',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='historicalshow',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Modifié le'),
        ),
        migrations.AlterField(
            model_name='historicalshow',
            name='youtube_channel_url',
            field=models.URLField(blank=True, verbose_name='URL de la chaîne YouTube'),
        ),
        migrations.AlterField(
            model_name='show',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='URL canonique (si le contenu est syndiqué depuis une autre source).', verbose_name='URL canonique'),
        ),
        migrations.AlterField(
            model_name='show',
            name='color',
            field=models.CharField(blank=True, default='#3D53EA', help_text="Couleur d'accent (hex).", max_length=9, verbose_name='Couleur (hex)'),
        ),
        migrations.AlterField(
            model_name='show',
            name='cover',
            field=models.ImageField(blank=True, help_text='Bannière large (16:9 recommandé).', null=True, upload_to='emissions/shows/cover/', verbose_name='Image de couverture'),
        ),
        migrations.AlterField(
            model_name='show',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='show',
            name='default_schedule',
            field=models.CharField(blank=True, help_text='Ex : « Lundi — Vendredi · 07h00 » (texte libre).', max_length=200, verbose_name='Horaire habituel'),
        ),
        migrations.AlterField(
            model_name='show',
            name='description',
            field=models.TextField(blank=True, help_text="Description longue de l'émission (page dédiée).", verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='show',
            name='host',
            field=models.CharField(blank=True, help_text='Animateur / pasteur principal.', max_length=200, verbose_name='Animateur'),
        ),
        migrations.AlterField(
            model_name='show',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False, help_text='Mise en avant sur la home / rubriques.', verbose_name='Mis en avant'),
        ),
        migrations.AlterField(
            model_name='show',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo transparent (carte, footer).', null=True, upload_to='emissions/shows/logo/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='show',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Description meta (≤ 180 caractères).', max_length=180, verbose_name='Description SEO'),
        ),
        migrations.AlterField(
            model_name='show',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Titre HTML (≤ 70 caractères). Si vide, `title` est utilisé.', max_length=70, verbose_name='Titre SEO'),
        ),
        migrations.AlterField(
            model_name='show',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Image Open Graph (1200×630 recommandé).', null=True, upload_to='seo/og/', verbose_name='Image Open Graph'),
        ),
        migrations.AlterField(
            model_name='show',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text="Ordre d'affichage (plus petit = plus en avant).", verbose_name="Ordre d'affichage"),
        ),
        migrations.AlterField(
            model_name='show',
            name='published_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Date de publication (auto-remplie ; peut être future pour programmer).', null=True, verbose_name='Publié le'),
        ),
        migrations.AlterField(
            model_name='show',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='show',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publié'), ('archived', 'Archivé')], db_index=True, default='draft', max_length=16, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='show',
            name='tagline',
            field=models.CharField(blank=True, help_text='Court résumé, utilisé dans les cartes et vignettes.', max_length=280, verbose_name='Accroche'),
        ),
        migrations.AlterField(
            model_name='show',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='show',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Modifié le'),
        ),
        migrations.AlterField(
            model_name='show',
            name='youtube_channel_url',
            field=models.URLField(blank=True, verbose_name='URL de la chaîne YouTube'),
        ),
    ]
