# Generated by Django 5.0.7 on 2026-07-10 18:17

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0003_alter_category_color_alter_category_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='episode_number',
            field=models.PositiveIntegerField(blank=True, help_text="Position de l'épisode au sein de la série (1, 2, 3…).", null=True, verbose_name='Numéro dans la série'),
        ),
        migrations.AddField(
            model_name='historicalepisode',
            name='episode_number',
            field=models.PositiveIntegerField(blank=True, help_text="Position de l'épisode au sein de la série (1, 2, 3…).", null=True, verbose_name='Numéro dans la série'),
        ),
        migrations.CreateModel(
            name='HistoricalSeries',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Modifié le')),
                ('slug', models.SlugField(blank=True, max_length=220, verbose_name='Slug')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publié'), ('archived', 'Archivé')], db_index=True, default='draft', max_length=16, verbose_name='Statut')),
                ('published_at', models.DateTimeField(blank=True, db_index=True, help_text='Date de publication (auto-remplie ; peut être future pour programmer).', null=True, verbose_name='Publié le')),
                ('is_featured', models.BooleanField(db_index=True, default=False, help_text='Mise en avant sur la home / rubriques.', verbose_name='Mis en avant')),
                ('meta_title', models.CharField(blank=True, help_text='Titre HTML (≤ 70 caractères). Si vide, `title` est utilisé.', max_length=70, verbose_name='Titre SEO')),
                ('meta_description', models.CharField(blank=True, help_text='Description meta (≤ 180 caractères).', max_length=180, verbose_name='Description SEO')),
                ('og_image', models.TextField(blank=True, help_text='Image Open Graph (1200×630 recommandé).', max_length=100, null=True, verbose_name='Image Open Graph')),
                ('canonical_url', models.URLField(blank=True, help_text='URL canonique (si le contenu est syndiqué depuis une autre source).', verbose_name='URL canonique')),
                ('title', models.CharField(max_length=220, verbose_name='Titre')),
                ('theme', models.CharField(blank=True, help_text='Le fil rouge de la série (ex : « La foi qui déplace les montagnes »).', max_length=280, verbose_name='Thème général')),
                ('description', models.TextField(blank=True, help_text='Présentation longue affichée en tête de la série.', verbose_name='Description')),
                ('cover', models.TextField(blank=True, help_text='Bannière large (16:9 recommandé).', max_length=100, null=True, verbose_name='Image de couverture')),
                ('starts_on', models.DateField(blank=True, help_text='Date de début de la série (ex : début du mois).', null=True, verbose_name='Début')),
                ('ends_on', models.DateField(blank=True, help_text='Date de fin (optionnelle — laissez vide si la série est en cours).', null=True, verbose_name='Fin')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text="Ordre d'affichage parmi les séries du même show.", verbose_name="Ordre d'affichage")),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('show', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='emissions.show', verbose_name='Émission')),
            ],
            options={
                'verbose_name': 'historical Série',
                'verbose_name_plural': 'historical Séries',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='Slug')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publié'), ('archived', 'Archivé')], db_index=True, default='draft', max_length=16, verbose_name='Statut')),
                ('published_at', models.DateTimeField(blank=True, db_index=True, help_text='Date de publication (auto-remplie ; peut être future pour programmer).', null=True, verbose_name='Publié le')),
                ('is_featured', models.BooleanField(db_index=True, default=False, help_text='Mise en avant sur la home / rubriques.', verbose_name='Mis en avant')),
                ('meta_title', models.CharField(blank=True, help_text='Titre HTML (≤ 70 caractères). Si vide, `title` est utilisé.', max_length=70, verbose_name='Titre SEO')),
                ('meta_description', models.CharField(blank=True, help_text='Description meta (≤ 180 caractères).', max_length=180, verbose_name='Description SEO')),
                ('og_image', models.ImageField(blank=True, help_text='Image Open Graph (1200×630 recommandé).', null=True, upload_to='seo/og/', verbose_name='Image Open Graph')),
                ('canonical_url', models.URLField(blank=True, help_text='URL canonique (si le contenu est syndiqué depuis une autre source).', verbose_name='URL canonique')),
                ('title', models.CharField(max_length=220, verbose_name='Titre')),
                ('theme', models.CharField(blank=True, help_text='Le fil rouge de la série (ex : « La foi qui déplace les montagnes »).', max_length=280, verbose_name='Thème général')),
                ('description', models.TextField(blank=True, help_text='Présentation longue affichée en tête de la série.', verbose_name='Description')),
                ('cover', models.ImageField(blank=True, help_text='Bannière large (16:9 recommandé).', null=True, upload_to='emissions/series/', verbose_name='Image de couverture')),
                ('starts_on', models.DateField(blank=True, help_text='Date de début de la série (ex : début du mois).', null=True, verbose_name='Début')),
                ('ends_on', models.DateField(blank=True, help_text='Date de fin (optionnelle — laissez vide si la série est en cours).', null=True, verbose_name='Fin')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text="Ordre d'affichage parmi les séries du même show.", verbose_name="Ordre d'affichage")),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='emissions.show', verbose_name='Émission')),
            ],
            options={
                'verbose_name': 'Série',
                'verbose_name_plural': 'Séries',
                'ordering': ['-starts_on', 'order', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='episode',
            name='series',
            field=models.ForeignKey(blank=True, help_text="Série d'enseignement à laquelle appartient cet épisode (optionnel).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='episodes', to='emissions.series', verbose_name='Série'),
        ),
        migrations.AddField(
            model_name='historicalepisode',
            name='series',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text="Série d'enseignement à laquelle appartient cet épisode (optionnel).", null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='emissions.series', verbose_name='Série'),
        ),
        migrations.AddIndex(
            model_name='series',
            index=models.Index(fields=['show', 'status'], name='emissions_s_show_id_1cb61e_idx'),
        ),
    ]
