# Generated by Django 5.0.7 on 2026-07-14 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0004_episode_episode_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalshow',
            name='host_photo',
            field=models.TextField(blank=True, help_text="Portrait de l'animateur, utilisé dans les grandes cartes de la page Émissions.", max_length=100, null=True, verbose_name="Photo de l'animateur"),
        ),
        migrations.AddField(
            model_name='show',
            name='host_photo',
            field=models.ImageField(blank=True, help_text="Portrait de l'animateur, utilisé dans les grandes cartes de la page Émissions.", null=True, upload_to='emissions/shows/host/', verbose_name="Photo de l'animateur"),
        ),
    ]
