# Generated by Django 5.0.7 on 2026-07-16 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0006_alter_episode_canonical_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(blank=True, default='', help_text="Couleur d'accent (hex, ex : #3D53EA).", max_length=9, verbose_name='Couleur (hex)'),
        ),
    ]
