# Generated by Django 5.0.7 on 2026-08-02 09:18

import apps.banners.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('message', models.CharField(help_text='Texte défilant affiché dans la bande rouge.', max_length=300, verbose_name='Message')),
                ('cta_label', models.CharField(blank=True, help_text="Ex. « S'inscrire ». Vide = pas de bouton.", max_length=60, verbose_name='Texte du bouton')),
                ('cta_url', models.CharField(blank=True, help_text='Interne : commence par « / » (ex. /evenements/mes-vacances-avec-ltl-tv). Externe : URL complète (ex. https://exemple.com).', max_length=500, validators=[apps.banners.validators.validate_internal_or_external_url], verbose_name='URL du bouton')),
                ('is_active', models.BooleanField(db_index=True, default=False, verbose_name='Actif')),
                ('starts_at', models.DateTimeField(blank=True, db_index=True, help_text='À partir de quand la bande est visible. Vide = immédiatement.', null=True, verbose_name='Visible à partir de')),
                ('ends_at', models.DateTimeField(blank=True, db_index=True, help_text="Jusqu'à quand (strict). Vide = indéfiniment.", null=True, verbose_name="Visible jusqu'à")),
            ],
            options={
                'verbose_name': 'Annonce',
                'verbose_name_plural': 'Annonces',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_active', 'starts_at', 'ends_at'], name='announcemen_is_acti_86eb03_idx')],
            },
        ),
        migrations.CreateModel(
            name='HistoricalAnnouncement',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Modifié le')),
                ('message', models.CharField(help_text='Texte défilant affiché dans la bande rouge.', max_length=300, verbose_name='Message')),
                ('cta_label', models.CharField(blank=True, help_text="Ex. « S'inscrire ». Vide = pas de bouton.", max_length=60, verbose_name='Texte du bouton')),
                ('cta_url', models.CharField(blank=True, help_text='Interne : commence par « / » (ex. /evenements/mes-vacances-avec-ltl-tv). Externe : URL complète (ex. https://exemple.com).', max_length=500, validators=[apps.banners.validators.validate_internal_or_external_url], verbose_name='URL du bouton')),
                ('is_active', models.BooleanField(db_index=True, default=False, verbose_name='Actif')),
                ('starts_at', models.DateTimeField(blank=True, db_index=True, help_text='À partir de quand la bande est visible. Vide = immédiatement.', null=True, verbose_name='Visible à partir de')),
                ('ends_at', models.DateTimeField(blank=True, db_index=True, help_text="Jusqu'à quand (strict). Vide = indéfiniment.", null=True, verbose_name="Visible jusqu'à")),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Annonce',
                'verbose_name_plural': 'historical Annonces',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
