# Generated by Django 5.0.7 on 2026-08-03 16:39

import apps.banners.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='cta_url',
            field=models.CharField(blank=True, help_text='Interne : commence par « / » (ex. /evenements/mes-vacances-avec-ltl-tv — utilisez la liste de suggestions ci-dessous). Externe : URL complète (ex. https://exemple.com).', max_length=500, validators=[apps.banners.validators.validate_internal_or_external_url], verbose_name='URL du bouton'),
        ),
        migrations.AlterField(
            model_name='historicalannouncement',
            name='cta_url',
            field=models.CharField(blank=True, help_text='Interne : commence par « / » (ex. /evenements/mes-vacances-avec-ltl-tv — utilisez la liste de suggestions ci-dessous). Externe : URL complète (ex. https://exemple.com).', max_length=500, validators=[apps.banners.validators.validate_internal_or_external_url], verbose_name='URL du bouton'),
        ),
    ]
